# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.find_or_create_by!(email: 'admin@example.com') do | adminUser |
	adminUser.password = 'password'
	adminUser.password_confirmation = 'password'
end if Rails.env.development?

User.find_or_create_by!(email: 'test@example.com') do | user |
	user.password = 'password'
	user.password_confirmation = 'password'
	user.confirmed_at = DateTime.now
	user.skip_confirmation!
end if Rails.env.development?

Gender.find_or_create_by!(char_desc: 'm', desc: 'Masculine') 
Gender.find_or_create_by!(char_desc: 'f', desc: 'Feminine') 
Gender.find_or_create_by!(char_desc: 'n', desc: 'Neutral') 

LanguageLevel.find_or_create_by!(level_code: 'A1')
LanguageLevel.find_or_create_by!(level_code: 'A2')
LanguageLevel.find_or_create_by!(level_code: 'B1')
LanguageLevel.find_or_create_by!(level_code: 'B2')
LanguageLevel.find_or_create_by!(level_code: 'C1')

Game.find_or_create_by!(game_code: 'falling_text') do | g |
	g.game_title = 'Falling Text'
	g.game_short_desc = 'Practice your german with a falling text game.'
	g.game_desc = 'Shoot down the words as they appear, by typing the answer before they hit the blocks. When all the blocks are smashed the game is over!' +
		'  Score extra points by shooting down the bonus words that fly horizontally across the screen. With each level progression, you will score more points,' +
		' so try to protect your blocks as long as possible to achieve the highest scores!. You can choose between practising vocabulary or conjugation.' +
		' For Vocabulary the text displayed will be in English, type in the German translation to shoot the word down. For conjugation practice, ' +
		'a verb will be displayed in the infinitive, type it in the corresponding conjugated form to shoot the words.'
end

NOUNS = [{ gender:"m", word: "Abend", english: "evening", level: "A1"},
{ gender:"n", word: "Abendbrot", english: "evening meal", level: "A2"},
{ gender:"n", word: "Angebot", english: "offer / deal", level: "A1"},
{ gender:"f", word: "Adresse", english: "address", level: "A1"},
{ gender:"f", word: "Abfahrt", english: "departure", level: "A1"},
{ gender:"m", word: "Abfall", english: "Trash", level: "A1"},
{ gender:"f", word: "Ampel", english: "traffic lights", level: "A1"},
{ gender:"m", word: "Apfel", english: "apple", level: "A1"},
{ gender:"f", word: "Apotheke", english: "pharmacy", level: "A1"},
{ gender:"m", word: "Arzt", english: "Doctor (male)", level: "A1"},
{ gender:"f", word: "Arbeit", english: "work", level: "A1"},
{ gender:"f", word: "Aufgabe", english: "exercise", level: "A1"},
{ gender:"m", word: "Aufschnitt", english: "cold sliced meat", level: "A1"},
{ gender:"n", word: "Auge", english: "eye", level: "A1"},
{ gender:"n", word: "Ausland", english: "overseas/abroad", level: "A1"},
{ gender:"f", word: "Aussicht", english: "view", level: "A1"},
{ gender:"m", word: "Arm", english: "poor/poverty", level: "A2"},
{ gender:"n", word: "Auto", english: "car", level: "A1"},
{ gender:"f", word: "Bäckerei", english: "bakery", level: "A1"},
{ gender:"n", word: "Bad", english: "bath", level: "A1"},
{ gender:"n", word: "Baby", english: "baby", level: "A1"},
{ gender:"m", word: "Bahnhof", english: "train station", level: "A1"},
{ gender:"n", word: "Bank", english: "Bank", level: "A1"},
{ gender:"m", word: "Bauch", english: "stomach", level: "A1"},
{ gender:"m", word: "Baum", english: "tree", level: "A1"},
{ gender:"n", word: "Bein", english: "leg", level: "A1"},
{ gender:"m", word: "Berg", english: "mountain", level: "A1"},
{ gender:"n", word: "Bett", english: "bed", level: "A1"},
{ gender:"m", word: "Beruf", english: "Job", level: "A1"},
{ gender:"n", word: "Bier", english: "beer", level: "A1"},
{ gender:"n", word: "Bild", english: "picture", level: "A1"},
{ gender:"f", word: "Blume", english: "flower", level: "A1"},
{ gender:"n", word: "Boot", english: "boat", level: "A1"},
{ gender:"m", word: "Brief", english: "letter", level: "A1"},
{ gender:"f", word: "Brille", english: "pair of glasses", level: "A1"},
{ gender:"n", word: "Birne", english: "pear", level: "A1"},
{ gender:"n", word: "Brot", english: "bread", level: "A1"},
{ gender:"n", word: "Brötchen", english: "bread roll", level: "A1"},
{ gender:"f", word: "Brücke", english: "bridge", level: "A1"},
{ gender:"m", word: "Bruder", english: "brother", level: "A1"},
{ gender:"n", word: "Buch", english: "book", level: "A1"},
{ gender:"f", word: "Burg", english: "castle/ fortress", level: "A1"},
{ gender:"n", word: "Büro", english: "office", level: "A1"},
{ gender:"m", word: "Campingplatz", english: "camping ground", level: "A1"},
{ gender:"m", word: "Cousin", english: "Cousin (male)", level: "A2"},
{ gender:"f", word: "Cousine", english: "Cousin (female)", level: "A2"},
{ gender:"m", word: "Direktor", english: "principal (male)", level: "A2"},
{ gender:"f", word: "Directorin", english: "principal (female)", level: "A2"},
{ gender:"m", word: "Dom", english: "cathedral", level: "A1"},
{ gender:"n", word: "Dorf", english: "village", level: "A1"},
{ gender:"f", word: "Ecke", english: "corner", level: "A1"},
{ gender:"n", word: "Ei", english: "egg", level: "A1"},
{ gender:"m", word: "Einwohner", english: "inhabitant", level: "A2"},
{ gender:"n", word: "Einzelkind", english: "only child", level: "A2"},
{ gender:"n", word: "Eis", english: "ice, icecream", level: "A1"},
{ gender:"f", word: "Eltern", english: "parents", level: "A1"},
{ gender:"n", word: "Erdgeschoss", english: "ground floor", level: "A1"},
{ gender:"m", word: "Erwachsene", english: "adult (male)", level: "A1"},
{ gender:"f", word: "Erwachsene", english: "adult (female)", level: "A1"},
{ gender:"m", word: "Euro", english: "Euro", level: "A1"},
{ gender:"n", word: "Fach", english: "Subject ( at school)", level: "A2"},
{ gender:"n", word: "Fahrrad", english: "bicycle", level: "A1"},
{ gender:"f", word: "Familie", english: "family", level: "A1"},
{ gender:"f", word: "Farbe", english: "colour", level: "A1"},
{ gender:"m", word: "Fehler", english: "mistake", level: "A1"},
{ gender:"n", word: "Fenster", english: "window", level: "A1"},
{ gender:"f", word: "Ferien", english: "holidays", level: "A1"},
{ gender:"m", word: "Fernseher", english: "television", level: "A1"},
{ gender:"n", word: "Fest", english: "festival", level: "A1"},
{ gender:"n", word: "Fieber", english: "fever", level: "A2"},
{ gender:"f", word: "Figur", english: "figure", level: "A2"},
{ gender:"f", word: "Flasche", english: "bottle", level: "A1"},
{ gender:"n", word: "Fleisch", english: "meat", level: "A1"},
{ gender:"m", word: "Flughafen", english: "airport", level: "A1"},
{ gender:"n", word: "Flugzeug", english: "plane", level: "A1"},
{ gender:"m", word: "Fluss", english: "river", level: "A1"},
{ gender:"f", word: "Frau", english: "woman/wife/Mrs", level: "A1"},
{ gender:"f", word: "Fremdsprache", english: "foreign language", level: "A2"},
{ gender:"m", word: "Freund", english: "boyfriend", level: "A1"},
{ gender:"f", word: "Freundin", english: "girlfriend", level: "A1"},
{ gender:"m", word: "Führerschein", english: "driver's licence", level: "A2"},
{ gender:"m", word: "Fuß", english: "foot", level: "A1"},
{ gender:"m", word: "Fußball", english: "football", level: "A1"},
{ gender:"m", word: "Garten", english: "garden", level: "A1"},
{ gender:"m", word: "Gast", english: "guest", level: "A1"},
{ gender:"n", word: "Gebäude", english: "building", level: "A1"},
{ gender:"m", word: "Geburtstag", english: "birthday", level: "A1"},
{ gender:"n", word: "Geld", english: "money", level: "A1"},
{ gender:"n", word: "Gemüse", english: "vegetables", level: "A1"},
{ gender:"n", word: "Geschäft", english: "shop/business", level: "A1"},
{ gender:"n", word: "Geschenk", english: "present", level: "A1"},
{ gender:"f", word: "Geschichte", english: "history/story", level: "A2"},
{ gender:"f", word: "Geschwister", english: "siblings", level: "A2"},
{ gender:"n", word: "Gesicht", english: "face", level: "A1"},
{ gender:"n", word: "Gleis", english: "track/platform", level: "A2"},
{ gender:"m", word: "Grad", english: "degrees", level: "A1"},
{ gender:"f", word: "Großmutter", english: "grandmother", level: "A1"},
{ gender:"m", word: "Großvater", english: "grandfather", level: "A1"},
{ gender:"f", word: "Großeltern", english: "grandparents", level: "A1"},
{ gender:"f", word: "Grundschule", english: "primary school", level: "A2"},
{ gender:"n", word: "Gymnasium", english: "academic high school", level: "A2"},
{ gender:"f", word: "Haare", english: "hair", level: "A1"},
{ gender:"m", word: "Hafen", english: "harbour", level: "A2"},
{ gender:"m", word: "Hals", english: "neck/throat", level: "A2"},
{ gender:"f", word: "Haltestelle", english: "(bus,tram) stop", level: "A2"},
{ gender:"n", word: "Handy", english: "mobile phone", level: "A1"},
{ gender:"f", word: "Hauptstadt", english: "capital city", level: "A1"},
{ gender:"n", word: "Haus", english: "house", level: "A1"},
{ gender:"f", word: "Hausaufgaben", english: "homework", level: "A1"},
{ gender:"n", word: "Haustier", english: "pet", level: "A1"},
{ gender:"n", word: "Heft", english: "exercise book", level: "A2"},
{ gender:"n", word: "Hemd", english: "shirt", level: "A1"},
{ gender:"m", word: "Herr", english: "gentleman/ Mr", level: "A1"},
{ gender:"f", word: "Hose", english: "pair of pants/trousers", level: "A1"},
{ gender:"m", word: "Hund", english: "dog", level: "A1"},
{ gender:"f", word: "Insel", english: "island", level: "A1"},
{ gender:"f", word: "Jacke", english: "jacket", level: "A1"},
{ gender:"n", word: "Jahr", english: "year", level: "A1"},
{ gender:"f", word: "Jahreszeit", english: "season", level: "A1"},
{ gender:"m", word: "Junge", english: "boy", level: "A1"},
{ gender:"m", word: "Kaffee", english: "coffee", level: "A1"},
{ gender:"f", word: "Karte", english: "card/ticket/map", level: "A1"},
{ gender:"f", word: "Kartoffeln", english: "potatoes", level: "A1"},
{ gender:"m", word: "Käse", english: "cheese", level: "A1"},
{ gender:"f", word: "Kasse", english: "checkout,till", level: "A1"},
{ gender:"f", word: "Katze", english: "cat", level: "A1"},
{ gender:"n", word: "Kaufhaus", english: "department store", level: "A2"},
{ gender:"m", word: "Keller", english: "cellar", level: "A1"},
{ gender:"f", word: "Kerze", english: "candle", level: "A1"},
{ gender:"n", word: "Kind", english: "child", level: "A1"},
{ gender:"f", word: "Kirche", english: "church", level: "A1"},
{ gender:"f", word: "Klamotten", english: "clothoes", level: "A1"},
{ gender:"f", word: "Klasse", english: "class", level: "A2"},
{ gender:"n", word: "Kleid", english: "dress", level: "A1"},
{ gender:"f", word: "Kneipe", english: "pub", level: "A1"},
{ gender:"m", word: "Koffer", english: "suitcase", level: "A1"},
{ gender:"m", word: "Kopf", english: "head", level: "A1"},
{ gender:"f", word: "Küche", english: "kitchen", level: "A1"},
{ gender:"m", word: "Kuchen", english: "cake", level: "A1"},
{ gender:"f", word: "Kuh", english: "cow", level: "A2"},
{ gender:"m", word: "Kühlschrank", english: "fridge", level: "A1"},
{ gender:"f", word: "Kunst", english: "art", level: "A1"},
{ gender:"f", word: "Küste", english: "coast", level: "A2"},
{ gender:"n", word: "Land", english: "Country/state", level: "A1"},
{ gender:"f", word: "Landschaft", english: "scenery, landscape", level: "A2"},
{ gender:"m", word: "Lärm", english: "noise", level: "A2"},
{ gender:"m", word: "Lehrer", english: "teacher (male)", level: "A1"},
{ gender:"f", word: "Leherin", english: "teacher (female)", level: "A1"},
{ gender:"f", word: "Leute", english: "people", level: "A1"},
{ gender:"n", word: "Mädchen", english: "girl", level: "A1"},
{ gender:"m", word: "Mann", english: "man,husband", level: "A1"},
{ gender:"m", word: "Mantel", english: "coat", level: "A1"},
{ gender:"m", word: "Markt", english: "market", level: "A1"},
{ gender:"f", word: "Mauer", english: "wall (outside)", level: "A2"},
{ gender:"f", word: "Maus", english: "mouse", level: "A2"},
{ gender:"n", word: "Meer", english: "sea", level: "A2"},
{ gender:"m", word: "Mensch", english: "person", level: "A1"},
{ gender:"f", word: "Milch", english: "milk", level: "A1"},
{ gender:"f", word: "Mitternacht", english: "midnight", level: "A1"},
{ gender:"m", word: "Mittag", english: "noon", level: "A1"},
{ gender:"n", word: "Mittagessen", english: "lunch", level: "A1"},
{ gender:"f", word: "Möbel", english: "furniture", level: "A1"},
{ gender:"m", word: "Monat", english: "month", level: "A1"},
{ gender:"m", word: "Morgen", english: "morning", level: "A1"},
{ gender:"m", word: "Mund", english: "mouth", level: "A1"},
{ gender:"f", word: "Mutter", english: "mother", level: "A1"},
{ gender:"m", word: "Nachbar", english: "neighbour", level: "A1"},
{ gender:"m", word: "Nachmittag", english: "afternoon", level: "A1"},
{ gender:"f", word: "Nachrichten", english: "news", level: "A2"},
{ gender:"f", word: "Nacht", english: "night", level: "A1"},
{ gender:"m", word: "Nachtisch", english: "dessert", level: "A1"},
{ gender:"f", word: "Nase", english: "nose", level: "A1"},
{ gender:"f", word: "Naturwissenschaften", english: "science", level: "A2"},
{ gender:"f", word: "Nordsee", english: "North Sea", level: "A2"},
{ gender:"f", word: "Note", english: "mark (school)/musical note", level: "A2"},
{ gender:"f", word: "Nudeln", english: "pasta/noodles", level: "A2"},
{ gender:"f", word: "Nummer", english: "number", level: "A1"},
{ gender:"n", word: "Ohr", english: "ear", level: "A1"},
{ gender:"m", word: "Onkel", english: "uncle", level: "A1"},
{ gender:"m", word: "Ort", english: "place", level: "A1"},
{ gender:"n", word: "Obst", english: "fruit", level: "A1"},
{ gender:"n", word: "Paar", english: "pair/couple", level: "A2"},
{ gender:"n", word: "Paket", english: "parcel", level: "A1"},
{ gender:"n", word: "Papier", english: "paper", level: "A1"},
{ gender:"f", word: "Pause", english: "interval/break", level: "A1"},
{ gender:"n", word: "Pferd", english: "horse", level: "A1"},
{ gender:"m", word: "Platz", english: "place", level: "A1"},
{ gender:"f", word: "Polizei", english: "police", level: "A1"},
{ gender:"f", word: "Prüfung", english: "exam, fries", level: "A2"},
{ gender:"n", word: "Rathaus", english: "town hall", level: "A1"},
{ gender:"f", word: "Richtung", english: "direction", level: "A2"},
{ gender:"m", word: "Rock", english: "skirt", level: "A1"},
{ gender:"m", word: "Rücken", english: "back", level: "A1"},
{ gender:"f", word: "Sache", english: "thing", level: "A2"},
{ gender:"m", word: "Saft", english: "juice", level: "A1"},
{ gender:"m", word: "Salat", english: "lettuce,salad", level: "A1"},
{ gender:"n", word: "Schaf", english: "sheep", level: "A2"},
{ gender:"m", word: "Schinken", english: "ham", level: "A2"},
{ gender:"n", word: "Schlafzimmer", english: "bedroom", level: "A1"},
{ gender:"n", word: "Schloss", english: "castle", level: "A1"},
{ gender:"f", word: "Schmerzen", english: "pain", level: "A1"},
{ gender:"m", word: "Schnupfen", english: "cold (illness)", level: "A2"},
{ gender:"f", word: "Schokolade", english: "chocolate", level: "A1"},
{ gender:"m", word: "Schrank", english: "cupboard", level: "A1"},
{ gender:"m", word: "Schuh", english: "shoe", level: "A1"},
{ gender:"f", word: "Schule", english: "school", level: "A1"},
{ gender:"m", word: "Schüler", english: "school student (male)", level: "A1"},
{ gender:"f", word: "Schülerin", english: "school student (female)", level: "A1"},
{ gender:"m", word: "Schlüssel", english: "key", level: "A1"},
{ gender:"f", word: "Schweiz", english: "Switzerland", level: "A2"},
{ gender:"f", word: "Schwester", english: "sister", level: "A1"},
{ gender:"n", word: "Schwimmbad", english: "swimming pool", level: "A1"},
{ gender:"m", word: "See", english: "lake", level: "A1"},
{ gender:"f", word: "Sehenswürdigkeiten", english: "tourist sites", level: "A2"},
{ gender:"f", word: "Seite", english: "side,page", level: "A2"},
{ gender:"m", word: "Senf", english: "mustard", level: "A2"},
{ gender:"m", word: "Sommer", english: "summer", level: "A1"},
{ gender:"f", word: "Sonne", english: "sun", level: "A1"},
{ gender:"m", word: "Sonnenbrand", english: "sunburn", level: "A1"},
{ gender:"f", word: "Stadt", english: "town,city", level: "A1"},
{ gender:"m", word: "Strift", english: "pen", level: "A2"},
{ gender:"f", word: "Stiefmutter", english: "stepmother", level: "A2"},
{ gender:"m", word: "Stiefvater", english: "stepfather", level: "A2"},
{ gender:"m", word: "Strand", english: "beach", level: "A1"},
{ gender:"f", word: "Straße", english: "street", level: "A1"},
{ gender:"f", word: "Straßenbahn", english: "tram", level: "A1"},
{ gender:"n", word: "Stück", english: "piece", level: "A1"},
{ gender:"m", word: "Stuhl", english: "chair", level: "A1"},
{ gender:"f", word: "Stunde", english: "hour", level: "A1"},
{ gender:"m", word: "Supermarkt", english: "supermarket", level: "A1"},
{ gender:"f", word: "Suppe", english: "soup", level: "A1"},
{ gender:"f", word: "Süβigkeiten", english: "sweets,lollies", level: "A2"},
{ gender:"m", word: "Tag", english: "day", level: "A1"},
{ gender:"n", word: "Tal", english: "valley", level: "B1"},
{ gender:"f", word: "Tante", english: "aunt", level: "A1"},
{ gender:"f", word: "Tasche", english: "bag,pocket", level: "A1"},
{ gender:"f", word: "Tasse", english: "cup", level: "A2"},
{ gender:"m", word: "Tee", english: "tea", level: "A1"},
{ gender:"m", word: "Teil", english: "part", level: "A2"},
{ gender:"m", word: "Teppich", english: "carpet", level: "A2"},
{ gender:"m", word: "Termin", english: "appointment", level: "A1"},
{ gender:"n", word: "Theater", english: "theatre", level: "A1"},
{ gender:"n", word: "Tier", english: "animal", level: "A1"},
{ gender:"m", word: "Tisch", english: "table", level: "A1"},
{ gender:"f", word: "Treppe", english: "stairs", level: "A1"},
{ gender:"f", word: "Tür", english: "door", level: "A1"},
{ gender:"f", word: "Tüte", english: "bag (shopping)", level: "A1"},
{ gender:"f", word: "Uhr", english: "clock", level: "A1"},
{ gender:"m", word: "Unterricht", english: "lesson/class", level: "A1"},
{ gender:"m", word: "Urlaub", english: "holiday", level: "A1"},
{ gender:"m", word: "Vater", english: "father", level: "A1"},
{ gender:"m", word: "Vogel", english: "bird", level: "A1"},
{ gender:"m", word: "Vormittag", english: "morning", level: "A2"},
{ gender:"m", word: "Vorname", english: "first name", level: "A1"},
{ gender:"m", word: "Wald", english: "forest", level: "A1"},
{ gender:"f", word: "Wand", english: "wall (inside)", level: "A1"},
{ gender:"n", word: "Wasser", english: "water", level: "A1"},
{ gender:"m", word: "Weg", english: "path", level: "A1"},
{ gender:"m", word: "Wein", english: "wine", level: "A1"},
{ gender:"f", word: "Welt", english: "world", level: "A1"},
{ gender:"n", word: "Wetter", english: "weather", level: "A1"},
{ gender:"f", word: "Woche", english: "week", level: "A1"},
{ gender:"n", word: "Wochenende", english: "weekend", level: "A1"},
{ gender:"f", word: "Wohnung", english: "flat,apartment", level: "A1"},
{ gender:"n", word: "Wort", english: "word", level: "A1"},
{ gender:"f", word: "Wurst", english: "sausage", level: "A2"},
{ gender:"f", word: "Zeit", english: "time", level: "A1"},
{ gender:"f", word: "Zeitung", english: "newspaper", level: "A1"},
{ gender:"n", word: "Zelt", english: "tent", level: "A2"},
{ gender:"n", word: "Zeugnis", english: "school report", level: "A2"},
{ gender:"n", word: "Zimmer", english: "room", level: "A1"},
{ gender:"m", word: "Zug", english: "train", level: "A2"},
{ gender:"m", word: "Montag", english: "Monday", level: "A1"},
{ gender:"m", word: "Dienstag", english: "Tuesday", level: "A1"},
{ gender:"m", word: "Mittwoch", english: "Wednesday", level: "A1"},
{ gender:"m", word: "Donnerstag", english: "Thursday", level: "A1"},
{ gender:"m", word: "Freitag", english: "Friday", level: "A1"},
{ gender:"m", word: "Samstag", english: "Saturday", level: "A1"},
{ gender:"m", word: "Sonntag", english: "Sunday", level: "A1"},
{ gender:"m", word: "Januar", english: "January", level: "A1"},
{ gender:"m", word: "Februar", english: "February", level: "A1"},
{ gender:"m", word: "März ", english: "March", level: "A1"},
{ gender:"m", word: "April", english: "April", level: "A1"},
{ gender:"m", word: "Mai", english: "May", level: "A1"},
{ gender:"m", word: "Juni", english: "June", level: "A1"},
{ gender:"m", word: "Juli", english: "July", level: "A1"},
{ gender:"m", word: "August", english: "August", level: "A1"},
{ gender:"m", word: "September", english: "September", level: "A1"},
{ gender:"m", word: "Oktober", english: "October", level: "A1"},
{ gender:"m", word: "November", english: "November", level: "A1"},
{ gender:"m", word: "Dezember", english: "December", level: "A1"},
{ gender:"m", word: "Fruhling", english: "Spring", level: "A1"},
{ gender:"m", word: "Sommer", english: "Summer", level: "A1"},
{ gender:"m", word: "Herbst", english: "Autumn", level: "A1"},
{ gender:"m", word: "Winter", english: "Winter", level: "A1"},
{ gender:"m", word: "Anzug", english: "Suit", level: "A2"},
{ gender:"m", word: "Angestellte", english: "Employees", level: "A2"},
{ gender:"m", word: "Arbeiter", english: "worker", level: "A2"},
{ gender:"m", word: "Ärger", english: "trouble", level: "A2"},
{ gender:"m", word: "Aufzug", english: "elevator", level: "A2"},
{ gender:"m", word: "Ausgang", english: "exit", level: "A2"},
{ gender:"f", word: "Ausstellung", english: "exhibition", level: "A2"},
{ gender:"m", word: "Ausweis", english: "ID card", level: "A2"},
{ gender:"f", word: "Bahn", english: "track/lane/railway", level: "A2"},
{ gender:"m", word: "Bauch", english: "stomach", level: "A2"},
{ gender:"m", word: "Berg", english: "mountain", level: "A2"},
{ gender:"m", word: "Beweber", english: "Applicants", level: "A2"},
{ gender:"n", word: "Blatt", english: "Leaf / sheet", level: "A2"},
{ gender:"f", word: "Bluse", english: "blouse", level: "A2"},
{ gender:"n", word: "Blut", english: "blood", level: "A2"},
{ gender:"f", word: "Bohne", english: "bean (food)", level: "A2"},
{ gender:"m", word: "Briefkasten", english: "Mailbox", level: "A2"},
{ gender:"m", word: "Briefumslag", english: "Envelope", level: "A2"},
{ gender:"n", word: "Dach", english: "roof", level: "A2"},
{ gender:"f", word: "Dauer", english: "duration", level: "A2"},
{ gender:"f", word: "Dose", english: "tin can", level: "A2"},
{ gender:"f", word: "Dusche", english: "shower", level: "A2"},
{ gender:"f", word: "Ehefrau", english: "wife", level: "A2"},
{ gender:"m", word: "Enklekind", english: "grandchild", level: "A2"},
{ gender:"n", word: "Erdgeschloss", english: "ground floor", level: "A2"},
{ gender:"f", word: "Erfahrung", english: "experience", level: "A2"},
{ gender:"f", word: "Erlaubnis", english: "permission", level: "A2"},
{ gender:"f", word: "Fabrik", english: "factory", level: "A2"},
{ gender:"f", word: "Fähre", english: "ferry", level: "A2"},
{ gender:"m", word: "Fahrplan", english: "timetable", level: "A2"},
{ gender:"f", word: "Farbe", english: "colour", level: "A2"},
{ gender:"m", word: "Fehler", english: "mistake", level: "A2"},
{ gender:"m", word: "Feiertag", english: "public holiday", level: "A2"},
{ gender:"n", word: "Fest", english: "festival", level: "A2"},
{ gender:"n", word: "Feuer", english: "fire", level: "A2"},
{ gender:"m", word: "Flur", english: "Hall / corridor", level: "A2"},
{ gender:"m", word: "Fluss", english: "river", level: "A2"},
{ gender:"m", word: "Frisör", english: "hairdresser", level: "A2"},
{ gender:"f", word: "Frist", english: "Deadline ", level: "A2"},
{ gender:"f", word: "Garantie", english: "guarantee", level: "A2"},
{ gender:"m", word: "Gast", english: "guest", level: "A2"},
{ gender:"f", word: "Gebühr", english: "Fee / charge", level: "A2"},
{ gender:"n", word: "Geburtsjahr", english: "birth year", level: "A2"},
{ gender:"n", word: "Gegenteil", english: "opposite", level: "A2"},
{ gender:"n", word: "Gericht", english: "dish (food)", level: "A2"},
{ gender:"f", word: "Gesundheit", english: "health", level: "A2"},
{ gender:"m", word: "Glückwunsch", english: "congratulation", level: "A2"},
{ gender:"f", word: "Grenze", english: "border", level: "A2"},
{ gender:"f", word: "Heimat", english: "homeland", level: "A2"},
{ gender:"f", word: "Heizung", english: "heater", level: "A2"},
{ gender:"n", word: "Hemd", english: "shirt", level: "A2"},
{ gender:"n", word: "Herz", english: "heart", level: "A2"},
{ gender:"f", word: "Hochzeit", english: "wedding", level: "A2"},
{ gender:"n", word: "Holz", english: "Wood", level: "A2"},
{ gender:"f", word: "Hose", english: "Pants", level: "A2"},
{ gender:"m", word: "Inhalt", english: "content", level: "A2"},
{ gender:"m", word: "Kalander", english: "calender", level: "A2"},
{ gender:"f", word: "Kanne", english: "Jug", level: "A2"},
{ gender:"f", word: "Kette", english: "chain", level: "A2"},
{ gender:"n", word: "Kino", english: "cinema", level: "A2"},
{ gender:"n", word: "Konto", english: "account", level: "A2"},
{ gender:"f", word: "Krankheit", english: "illness", level: "A2"},
{ gender:"m", word: "Kredit", english: "credit", level: "A2"},
{ gender:"m", word: "Kreis", english: "circle", level: "A2"},
{ gender:"f", word: "Kundigung", english: "Termination", level: "A2"},
{ gender:"m", word: "Laden", english: "shop/store", level: "A2"},
{ gender:"n", word: "Lager", english: "stock/warehouse", level: "A2"},
{ gender:"f", word: "Landschaft", english: "landscape/countryside", level: "A2"},
{ gender:"m", word: "Lohn", english: "wage/salary", level: "A2"},
{ gender:"n", word: "Mal", english: "Times", level: "A2"},
{ gender:"m", word: "Markt", english: "market", level: "A2"},
{ gender:"f", word: "Menge", english: "amount/quantity", level: "A2"},
{ gender:"n", word: "Metall", english: "Metal", level: "A2"},
{ gender:"f", word: "Million", english: "million", level: "A2"},
{ gender:"f", word: "Mitte", english: "center", level: "A2"},
{ gender:"f", word: "Mode", english: "Fashion", level: "A2"},
{ gender:"m", word: "Motor", english: "Motor", level: "A2"},
{ gender:"m", word: "Müll", english: "Trash", level: "A2"},
{ gender:"m", word: "Mund", english: "Mouth", level: "A2"},
{ gender:"f", word: "Nachrichten", english: "News", level: "A2"},
{ gender:"f", word: "Natur", english: "Nature", level: "A2"},
{ gender:"m", word: "Nebel", english: "Fog", level: "A2"},
{ gender:"n", word: "Plastik", english: "Plastic", level: "A2"},
{ gender:"n", word: "Prozent", english: "Percent", level: "A2"},
{ gender:"m", word: "Raucher", english: "Smoker", level: "A2"},
{ gender:"f", word: "Reinigung", english: "Cleaning", level: "A2"},
{ gender:"n", word: "Rind", english: "Beef", level: "A2"},
{ gender:"m", word: "Rücken", english: "back/spine", level: "A2"},
{ gender:"f", word: "Sache", english: "thing", level: "A2"},
{ gender:"n", word: "Schloss", english: "palace/castle", level: "A2"},
{ gender:"m", word: "Schnee", english: "snow", level: "A2"},
{ gender:"f", word: "Seife", english: "soap", level: "A2"},
{ gender:"f", word: "Sorge", english: "worry/concern", level: "A2"},
{ gender:"m", word: "Spaβ", english: "fun", level: "A2"},
{ gender:"f", word: "Spülmaschine", english: "dishwasher", level: "A2"},
{ gender:"f", word: "Stelle", english: "Job", level: "A2"},
{ gender:"m", word: "Strand", english: "beach", level: "A2"},
{ gender:"n", word: "Streichholz", english: "match stick", level: "A2"},
{ gender:"m", word: "Vermieter", english: "landlord/lessor", level: "A2"},
{ gender:"m", word: "Verein", english: "club", level: "A2"},
{ gender:"f", word: "Verbindung", english: "connection", level: "A2"},
{ gender:"f", word: "Versicherung", english: "insurance", level: "A2"},
{ gender:"n", word: "Werkzeug", english: "tool", level: "A2"},
{ gender:"f", word: "Wolke", english: "cloud", level: "A2"},
{ gender:"m", word: "Wunsch", english: "wish", level: "A2"},
{ gender:"f", word: "Zeitschrift", english: "magazine", level: "A2"},
{ gender:"m", word: "Zentimeter", english: "centimeter", level: "A2"},
{ gender:"f", word: "Zitrone", english: "lemon", level: "A2"},
{ gender:"m", word: "Zucker", english: "sugar", level: "A2"}]


NOUNS.each do | noun |
	n = Noun.find_or_initialize_by( word: noun[:word])
	g = Gender.find_by!(char_desc: noun[:gender])
	level = LanguageLevel.find_by!(level_code: noun[:level])
	n.language_level = level
	n.gender = g
	n.english = noun[:english]
	n.save!	
end

VERBS = [
	{ infinitive:"sein", ich:"bin", du: "bist", es: "ist", ihr: "seid", wir: "sind", Sie: "sind", english: "to be", Level: "A1", regular: "0", past_participle: "gewesen", auxiliary_verb: "sein"},
	{ infinitive:"werden", ich:"werde", du: "wirst", es: "wird", ihr: "werdet", wir: "werden", Sie: "werden", english: "to become", Level: "A2", regular: "0", past_participle: "geworden", auxiliary_verb: "sein"},
	{ infinitive:"haben", ich:"habe", du: "hast", es: "hat", ihr: "habt", wir: "haben", Sie: "haben", english: "to have", Level: "A1", regular: "0", past_participle: "gehabt", auxiliary_verb: "haben"},
	{ infinitive:"können", ich:"kann", du: "kannst", es: "kann", ihr: "könnt", wir: "können", Sie: "können", english: "to can\n to be able to", Level: "A1", regular: "0", past_participle: "gekonnt", auxiliary_verb: "haben"},
	{ infinitive:"müssen", ich:"muss", du: "musst", es: "muss", ihr: "müsst", wir: "müssen", Sie: "müssen", english: "to must", Level: "A1", regular: "0", past_participle: "gemusst", auxiliary_verb: "haben"},
	{ infinitive:"geben", ich:"gebe", du: "gibst", es: "gibt", ihr: "gebt", wir: "geben", Sie: "geben", english: "to give", Level: "A1", regular: "0", past_participle: "gegeben", auxiliary_verb: "haben"},
	{ infinitive:"sollen", ich:"soll", du: "sollst", es: "soll", ihr: "sollt", wir: "sollen", Sie: "sollen", english: "to should", Level: "A1", regular: "0", past_participle: "gesollt", auxiliary_verb: "haben"},
	{ infinitive:"sagen", ich:"sage", du: "sagst", es: "sagt", ihr: "sagt", wir: "sagen", Sie: "sagen", english: "to say", Level: "A1", regular: "1", past_participle: "gesagt", auxiliary_verb: "haben"},
	{ infinitive:"wollen", ich:"will", du: "willst", es: "will", ihr: "wollt", wir: "wollen", Sie: "wollen", english: "to want", Level: "A1", regular: "0", past_participle: "gewollt", auxiliary_verb: "haben"},
	{ infinitive:"kommen", ich:"komme", du: "kommst", es: "kommt", ihr: "kommt", wir: "kommen", Sie: "kommen", english: "to come", Level: "A1", regular: "0", past_participle: "gekommen", auxiliary_verb: "sein"},
	{ infinitive:"gehen", ich:"gehe", du: "gehst", es: "geht", ihr: "geht", wir: "gehen", Sie: "gehen", english: "to go \n to walk", Level: "A1", regular: "0", past_participle: "gegangen", auxiliary_verb: "sein"},
	{ infinitive:"machen", ich:"mache", du: "machst", es: "macht", ihr: "macht", wir: "machen", Sie: "machen", english: "to do", Level: "A1", regular: "1", past_participle: "gemacht", auxiliary_verb: "haben"},
	{ infinitive:"stehen", ich:"stehe", du: "stehst", es: "steht", ihr: "steht", wir: "stehen", Sie: "stehen", english: "to stand", Level: "A1", regular: "0", past_participle: "gestanden", auxiliary_verb: "haben"},
	{ infinitive:"sehen", ich:"sehe", du: "siehst", es: "sieht", ihr: "seht", wir: "sehen", Sie: "sehen", english: "to see", Level: "A1", regular: "0", past_participle: "gesehen", auxiliary_verb: "haben"},
	{ infinitive:"finden", ich:"finde", du: "findest", es: "findet", ihr: "findet", wir: "finden", Sie: "finden", english: "to find", Level: "A1", regular: "0", past_participle: "gefunden", auxiliary_verb: "haben"},
	{ infinitive:"bleiben", ich:"bleibe", du: "bleibst", es: "bleibt", ihr: "bleibt", wir: "bleiben", Sie: "bleiben", english: "to stay", Level: "A1", regular: "0", past_participle: "geblieben", auxiliary_verb: "sein"},
	{ infinitive:"liegen", ich:"liege", du: "liegst", es: "liegt", ihr: "liegt", wir: "liegen", Sie: "liegen", english: "to lie down", Level: "A1", regular: "0", past_participle: "gelegen", auxiliary_verb: "haben"},
	{ infinitive:"stellen", ich:"stelle", du: "stellst", es: "stellt", ihr: "stellt", wir: "stellen", Sie: "stellen", english: "to put", Level: "A1", regular: "1", past_participle: "gestellt", auxiliary_verb: "haben"},
	{ infinitive:"nehmen", ich:"nehme", du: "nimmst", es: "nimmt", ihr: "nehmt", wir: "nehmen", Sie: "nehmen", english: "to take", Level: "A1", regular: "0", past_participle: "genommen", auxiliary_verb: "haben"},
	{ infinitive:"dürfen", ich:"darf", du: "darfst", es: "darf", ihr: "dürft ", wir: "dürfen", Sie: "dürfen", english: "to be allowed", Level: "A1", regular: "0", past_participle: "gedurft", auxiliary_verb: "haben"},
	{ infinitive:"bringen", ich:"bringe", du: "bringst", es: "bringt", ihr: "bringt", wir: "bringen", Sie: "bringen", english: "to bring", Level: "A1", regular: "0", past_participle: "gebracht", auxiliary_verb: "haben"},
	{ infinitive:"halten", ich:"halte", du: "hältst", es: "hält", ihr: "haltet", wir: "halten", Sie: "halten", english: "to hold", Level: "A2", regular: "0", past_participle: "gehalten", auxiliary_verb: "haben"},
	{ infinitive:"spielen", ich:"spiele", du: "spielst", es: "spielt", ihr: "spielt", wir: "spielen", Sie: "spielen", english: "to play", Level: "A1", regular: "1", past_participle: "gespielt", auxiliary_verb: "haben"},
	{ infinitive:"heißen", ich:"heiße", du: "heißt", es: "heißt", ihr: "heißt", wir: "heißen", Sie: "heißen", english: "to be called", Level: "A1", regular: "0", past_participle: "geheißt", auxiliary_verb: "haben"},
	{ infinitive:"wissen", ich:"weiß", du: "weißt", es: "weiß", ihr: "wisst", wir: "wissen", Sie: "wissen", english: "to know", Level: "A1", regular: "0", past_participle: "gewusst", auxiliary_verb: "haben"},
	{ infinitive:"erklären", ich:"erkläre", du: "erklärst", es: "erklärt", ihr: "erklärt", wir: "erklären", Sie: "erklären", english: "to explain", Level: "A1", regular: "1", past_participle: "erklären", auxiliary_verb: "haben"},
	{ infinitive:"gehören", ich:"gehöre", du: "gehörst", es: "gehört", ihr: "gehört", wir: "gehören", Sie: "gehören", english: "to belong", Level: "A2", regular: "1", past_participle: "gehört ", auxiliary_verb: "haben"},
	{ infinitive:"beginnen", ich:"beginne", du: "beginnst", es: "beginnt", ihr: "beginnt", wir: "beginnen", Sie: "beginnen", english: "to begin", Level: "A1", regular: "0", past_participle: "begonnen", auxiliary_verb: "haben"},
	{ infinitive:"sprechen", ich:"spreche", du: "sprichst", es: "sprict", ihr: "sprecht", wir: "sprechen", Sie: "sprechen", english: "to speak", Level: "A1", regular: "0", past_participle: "gesprochen", auxiliary_verb: "haben"},
	{ infinitive:"tun", ich:"tue", du: "tust", es: "tut", ihr: "tut", wir: "tun", Sie: "tun", english: "to do", Level: "A1", regular: "0", past_participle: "getan", auxiliary_verb: "haben"},
	{ infinitive:"mögen", ich:"mag", du: "magst", es: "mag", ihr: "mögt", wir: "mögen", Sie: "mögen", english: "to like", Level: "A1", regular: "0", past_participle: "gemocht", auxiliary_verb: "haben"},
	{ infinitive:"gewinnen", ich:"gewinne", du: "gewinnst", es: "gewinnt", ihr: "gewinnt", wir: "gewinnen", Sie: "gewinnen", english: "to win", Level: "A1", regular: "0", past_participle: "gewonnen", auxiliary_verb: "haben"},
	{ infinitive:"bekommen", ich:"bekomme", du: "bekommst", es: "bekommt", ihr: "bekommt", wir: "bekommen", Sie: "bekommen", english: "to get", Level: "A1", regular: "1", past_participle: "bekommen", auxiliary_verb: "haben"},
	{ infinitive:"schreiben", ich:"schreibe", du: "schreibst", es: "schreibt", ihr: "schreibt", wir: "schreiben", Sie: "schreiben", english: "to write", Level: "A1", regular: "0", past_participle: "geschrieben", auxiliary_verb: "haben"},
	{ infinitive:"arbeiten", ich:"arbeite", du: "arbeitest", es: "arbeitet", ihr: "arbeitet", wir: "arbeiten", Sie: "arbeiten", english: "to work", Level: "A1", regular: "0", past_participle: "gearbeitet", auxiliary_verb: "haben"},
	{ infinitive:"treffen", ich:"treffe", du: "triffst", es: "trifft", ihr: "trefft", wir: "treffen", Sie: "treffen", english: "to meet", Level: "A1", regular: "0", past_participle: "getroffen", auxiliary_verb: "haben"},
	{ infinitive:"zahlen", ich:"zahle", du: "zahlst", es: "zahlt", ihr: "zahlt", wir: "zahlen", Sie: "zahlen", english: "to pay", Level: "A1", regular: "1", past_participle: "gezahlt", auxiliary_verb: "haben"},
	{ infinitive:"leben", ich:"lebe", du: "lebst", es: "lebt", ihr: "lebt", wir: "leben", Sie: "leben", english: "to live", Level: "A1", regular: "1", past_participle: "gelebt", auxiliary_verb: "haben"},
	{ infinitive:"laufen", ich:"laufe", du: "läufst", es: "läuft", ihr: "lauft", wir: "laufen", Sie: "laufen", english: "to walk", Level: "A1", regular: "0", past_participle: "gelaufen", auxiliary_verb: "sein"},
	{ infinitive:"brauchen", ich:"brauche", du: "brauchst", es: "braucht", ihr: "braucht", wir: "brauchen", Sie: "brauchen", english: "to need", Level: "A1", regular: "0", past_participle: "gebraucht", auxiliary_verb: "haben"},
	{ infinitive:"feiern", ich:"feiere", du: "feierst", es: "feiert", ihr: "feiert", wir: "feiern", Sie: "feiern", english: "to celebrate", Level: "A1", regular: "1", past_participle: "gefeiert", auxiliary_verb: "haben"},
	{ infinitive:"fahren", ich:"fahre", du: "fährst", es: "fährt", ihr: "fahrt", wir: "fahren", Sie: "fahren", english: "to drive", Level: "A1", regular: "0", past_participle: "gefahren", auxiliary_verb: "sein"},
	{ infinitive:"suchen", ich:"suche", du: "suchst", es: "sucht", ihr: "sucht", wir: "suchen", Sie: "suchen", english: "to search", Level: "A1", regular: "1", past_participle: "gesucht", auxiliary_verb: "haben"},
	{ infinitive:"legen", ich:"lege", du: "legst", es: "legt", ihr: "legt", wir: "legen", Sie: "legen", english: "to put", Level: "A1", regular: "1", past_participle: "gelegt", auxiliary_verb: "haben"},
	{ infinitive:"glauben", ich:"glaube", du: "glaubst", es: "glaubt", ihr: "glaubt", wir: "glauben", Sie: "glauben", english: "to believe", Level: "A1", regular: "1", past_participle: "geglaubt", auxiliary_verb: "haben"},
	{ infinitive:"scheinen", ich:"scheine", du: "scheinst", es: "scheint", ihr: "scheint", wir: "scheinen", Sie: "scheinen", english: "to seem", Level: "A2", regular: "1", past_participle: "gescheinen", auxiliary_verb: "haben"},
	{ infinitive:"schließen", ich:"schließe", du: "schließt", es: "schließe", ihr: "schließe", wir: "schließen", Sie: "schließen", english: "to close", Level: "A1", regular: "0", past_participle: "geschlossen", auxiliary_verb: "haben"},
	{ infinitive:"fehlen", ich:"fehle", du: "fehlst", es: "fehlt", ihr: "fehlt", wir: "fehlen", Sie: "fehlen", english: "to lack \n to be wrong", Level: "A2", regular: "1", past_participle: "gefehlt", auxiliary_verb: "haben"},
	{ infinitive:"kennen", ich:"kenne", du: "kennst", es: "kennt", ihr: "kennt", wir: "kennen", Sie: "kennen", english: "to know", Level: "A1", regular: "0", past_participle: "gekannt", auxiliary_verb: "haben"},
	{ infinitive:"fragen", ich:"frage", du: "fragst", es: "fragt", ihr: "fragt", wir: "fragen", Sie: "fragen", english: "to ask", Level: "A1", regular: "1", past_participle: "gefragt", auxiliary_verb: "haben"},
	{ infinitive:"holen", ich:"hole", du: "holst", es: "holt", ihr: "holt", wir: "holen", Sie: "holen", english: "to fetch", Level: "A1", regular: "1", past_participle: "geholt", auxiliary_verb: "haben"},
	{ infinitive:"ankommen", ich:"komme an", du: "kommst an", es: "kommt an", ihr: "kommt an", wir: "kommen an", Sie: "kommen an", english: "to arrive", Level: "A1", regular: "0", past_participle: "angekommen", auxiliary_verb: "sein"},
	{ infinitive:"anmachen", ich:"mache", du: "machst an", es: "macht an", ihr: "macht an", wir: "machen an", Sie: "machen an", english: "to turn on", Level: "A1", regular: "1", past_participle: "angemacht", auxiliary_verb: "haben"},
	{ infinitive:"anrufen", ich:"rufe an", du: "rufst an", es: "ruft an", ihr: "ruft an", wir: "rufen an", Sie: "anrufen", english: "to call", Level: "A1", regular: "0", past_participle: "angerufen", auxiliary_verb: "haben"},
	{ infinitive:"anziehen", ich:"ziehe an", du: "ziehst an", es: "zieht an", ihr: "zieht an", wir: "ziehen an", Sie: "ziehen an", english: "to pull", Level: "A1", regular: "0", past_participle: "angezogen", auxiliary_verb: "haben"},
	{ infinitive:"anklicken", ich:"klicke an", du: "klickst an", es: "klickt an", ihr: "klickt an", wir: "klicken an", Sie: "klicken an", english: "to click", Level: "A1", regular: "1", past_participle: "angeklickt", auxiliary_verb: "haben"},
	{ infinitive:"ankreuzen", ich:"kreuze an", du: "kreuzt an", es: "kreuzt an", ihr: "kreuzt an", wir: "kreuzen an", Sie: "kreuzen an", english: "to mark with a cross", Level: "A1", regular: "1", past_participle: "angekreuzt", auxiliary_verb: "haben"},
	{ infinitive:"aufstehen", ich:"stehe auf", du: "stehst auf", es: "steht auf", ihr: "steht auf", wir: "stehen auf", Sie: "stehen auf", english: "to get up", Level: "A1", regular: "1", past_participle: "aufgestanden", auxiliary_verb: "sein"},
	{ infinitive:"ausfüllen", ich:"fülle aus", du: "füllst aus", es: "füllt aus", ihr: "füllt aus", wir: "füllen aus", Sie: "füllen aus", english: "to complete", Level: "A1", regular: "1", past_participle: "ausgefüllt", auxiliary_verb: "haben"},
	{ infinitive:"aussehen", ich:"sehe aus", du: "siehst aus", es: "sieht aus", ihr: "seht aus", wir: "sehen aus", Sie: "aussehen", english: "to look", Level: "A1", regular: "0", past_participle: "ausgesehen", auxiliary_verb: "sein"},
	{ infinitive:"aussteigen", ich:"steige aus", du: "steigst aus", es: "steigt aus", ihr: "steigt aus", wir: "steigen aus", Sie: "aussteigen", english: "to get out", Level: "A1", regular: "0", past_participle: "ausgestiegen ", auxiliary_verb: "sein"},
	{ infinitive:"bedeuten", ich:"bedeute", du: "bedeutest", es: "bedeutet", ihr: "bedeutet", wir: "bedeuten", Sie: "bedeuten", english: "to mean", Level: "A1", regular: "1", past_participle: "bedeutete", auxiliary_verb: "haben"},
	{ infinitive:"beginnen", ich:"beginne", du: "beginnst", es: "beginnt", ihr: "beginnt", wir: "beginnen", Sie: "beginnen", english: "to begin", Level: "A1", regular: "0", past_participle: "begonnen", auxiliary_verb: "haben"},
	{ infinitive:"bekommen", ich:"bekomme", du: "bekommst", es: "bekommt", ihr: "bekommt", wir: "bekommen", Sie: "bekommen", english: "to receive", Level: "A1", regular: "0", past_participle: "bekommen", auxiliary_verb: "haben"},
	{ infinitive:"bestellen", ich:"bestelle", du: "bestellst", es: "bestellt", ihr: "bestellt", wir: "bestellen", Sie: "bestellen", english: "to order", Level: "A1", regular: "1", past_participle: "bestellt", auxiliary_verb: "haben"},
	{ infinitive:"bezahlen", ich:"bezahle", du: "bezahlst", es: "bezahlt", ihr: "bezahlt", wir: "bezahlen", Sie: "bezahlen", english: "to pay", Level: "A1", regular: "1", past_participle: "bezahlt", auxiliary_verb: "haben"},
	{ infinitive:"buchstabieren", ich:"buchstabiere", du: "buchstabierst", es: "buchstabiert", ihr: "buchstabiert", wir: "buchstabieren", Sie: "buchstabieren", english: "to spell", Level: "A1", regular: "1", past_participle: "buchstabiert", auxiliary_verb: "haben"},
	{ infinitive:"danken", ich:"danke", du: "dankst", es: "dankt", ihr: "dankt", wir: "danken", Sie: "danken", english: "to thank", Level: "A1", regular: "1", past_participle: "gedankt", auxiliary_verb: "haben"},
	{ infinitive:"drucken", ich:"drucke", du: "druckst", es: "druckt", ihr: "druckt", wir: "drucken", Sie: "drucken", english: "to press", Level: "A1", regular: "1", past_participle: "gedruckt", auxiliary_verb: "haben"},
	{ infinitive:"einkaufen", ich:"kaufe ein", du: "kaufst ein", es: "kauft ein", ihr: "kauft ein", wir: "kaufen ein", Sie: "einkaufen", english: "to show", Level: "A1", regular: "1", past_participle: "eingekauft", auxiliary_verb: "haben"},
	{ infinitive:"einladen", ich:"lade ein", du: "lädst ein", es: "lädt ein", ihr: "ladet ein", wir: "laden ein", Sie: "einladen", english: "to invite", Level: "A1", regular: "0", past_participle: "eingeladen", auxiliary_verb: "haben"},
	{ infinitive:"empfehlen", ich:"empfehle", du: "empfiehlst", es: "empfiehlt", ihr: "empfehlt", wir: "empfehlen", Sie: "empfehlen", english: "to recommend", Level: "A2", regular: "0", past_participle: "empfohlen", auxiliary_verb: "haben"},
	{ infinitive:"einsteigen", ich:"steige ein", du: "steigst ein", es: "steigt ein", ihr: "steigt ein", wir: "steigen ein", Sie: "einsteigen", english: "to enter", Level: "A1", regular: "0", past_participle: "geingestiegen", auxiliary_verb: "sein"},
	{ infinitive:"fliegen", ich:"fliege", du: "fliegst", es: "fliegt", ihr: "fliegt", wir: "fliegen", Sie: "fliegen", english: "to fly", Level: "A1", regular: "0", past_participle: "geflogen", auxiliary_verb: "sein"},
	{ infinitive:"grillen", ich:"grille", du: "grillst", es: "grillt", ihr: "grillt", wir: "grillen", Sie: "grillen", english: "to grill", Level: "A1", regular: "1", past_participle: "gegrillt", auxiliary_verb: "haben"},
	{ infinitive:"gratulieren", ich:"gratuliere", du: "gratulierst", es: "gratuliert", ihr: "gratuliert", wir: "graturlieren", Sie: "gratulieren", english: "to congratulate", Level: "A1", regular: "1", past_participle: "gratuliert", auxiliary_verb: "haben"},
	{ infinitive:"heiraten", ich:"heirate", du: "heiratest", es: "heiratet", ihr: "heiratet", wir: "heiraten", Sie: "heiraten", english: "to marry", Level: "A1", regular: "1", past_participle: "geheiratet", auxiliary_verb: "haben"},
	{ infinitive:"helfen", ich:"helfe", du: "hilfst", es: "hilft", ihr: "helft", wir: "helfen", Sie: "helfen", english: "to help", Level: "A1", regular: "0", past_participle: "geholfen", auxiliary_verb: "haben"},
	{ infinitive:"kaufen", ich:"kaufe", du: "kaufst", es: "kauft", ihr: "kauft", wir: "kaufen", Sie: "kaufen", english: "to buy", Level: "A1", regular: "1", past_participle: "gekauft", auxiliary_verb: "haben"},
	{ infinitive:"kümmern", ich:"kümme", du: "kümmerst", es: "kümmert", ihr: "kümmt", wir: "kümmern", Sie: "kümmern", english: "to take care of", Level: "A1", regular: "1", past_participle: "gekümmert", auxiliary_verb: "haben"},
	{ infinitive:"lachen", ich:"lache", du: "lachst", es: "lacht", ihr: "lacht", wir: "lachen", Sie: "lachen", english: "to laugh", Level: "A1", regular: "1", past_participle: "gelacht", auxiliary_verb: "haben"},
	{ infinitive:"lieben", ich:"liebe", du: "liebst", es: "liebt", ihr: "liebt", wir: "lieben", Sie: "lieben", english: "to love", Level: "A1", regular: "1", past_participle: "geliebt", auxiliary_verb: "haben"},
	{ infinitive:"lernen", ich:"lerne", du: "lernst", es: "lernt", ihr: "lernt", wir: "lernen", Sie: "lernen", english: "to learn", Level: "A1", regular: "1", past_participle: "gelernt", auxiliary_verb: "haben"},
	{ infinitive:"liegen", ich:"liege", du: "liegst", es: "liegt", ihr: "liegt", wir: "liegen", Sie: "liegen", english: "to lie down", Level: "A1", regular: "0", past_participle: "gelegen", auxiliary_verb: "haben"},
	{ infinitive:"reisen", ich:"reise", du: "reist", es: "reist", ihr: "reist", wir: "reisen", Sie: "reisen", english: "to travel", Level: "A1", regular: "1", past_participle: "gereist", auxiliary_verb: "sein"},
	{ infinitive:"reparieren", ich:"repariere", du: "reparierst", es: "repariert", ihr: "repariert", wir: "reparieren", Sie: "reparieren", english: "to repair", Level: "A1", regular: "1", past_participle: "repariert", auxiliary_verb: "haben"},
	{ infinitive:"schmecken", ich:"schmeke", du: "schmeckst", es: "schmeckt", ihr: "schmeckt", wir: "schmecken", Sie: "schmecken", english: "to taste", Level: "A1", regular: "1", past_participle: "geschmeckt", auxiliary_verb: "haben"},
	{ infinitive:"sitzen", ich:"sitze", du: "sitzt", es: "sizt", ihr: "sitzen", wir: "sitzen", Sie: "sitzen", english: "to sit down", Level: "A1", regular: "0", past_participle: "gesessen", auxiliary_verb: "haben"},
	{ infinitive:"tanzen", ich:"tanze", du: "tanzt", es: "tanzt", ihr: "tanzt", wir: "tanzen", Sie: "tanzen", english: "to dance", Level: "A1", regular: "1", past_participle: "getanzt", auxiliary_verb: "haben"},
	{ infinitive:"verstehen", ich:"verstehe", du: "verstehst", es: "versteht", ihr: "versteht", wir: "verstehen", Sie: "verstehen", english: "to understand", Level: "A1", regular: "0", past_participle: "verstanden", auxiliary_verb: "haben"},
	{ infinitive:"verkaufen", ich:"verkaufe", du: "verkaufst", es: "verkauft", ihr: "verkauft", wir: "verkaufen", Sie: "verkaufen", english: "to sell", Level: "A1", regular: "1", past_participle: "gekauft", auxiliary_verb: "haben"},
	{ infinitive:"vorstellen", ich:"stelle vor", du: "stellst vor", es: "stellt vor", ihr: "stellt vor", wir: "stellen vor", Sie: "vorstellen", english: "to introduce", Level: "A1", regular: "1", past_participle: "vorgestellt", auxiliary_verb: "haben"},
	{ infinitive:"vorschlagen", ich:"schlage vor", du: "schlägst vor", es: "schlägt vor", ihr: "schlagt vor", wir: "schlagen vor", Sie: "vorschlagen", english: "to propose", Level: "A1", regular: "0", past_participle: "vorgeschlagen", auxiliary_verb: "haben"},
	{ infinitive:"wandern", ich:"wande", du: "wanderst", es: "wandert", ihr: "wandert", wir: "wandern", Sie: "wandern", english: "to hike", Level: "A1", regular: "1", past_participle: "gewandert", auxiliary_verb: "sein"},
	{ infinitive:"waschen", ich:"wasche", du: "wäschst", es: "wäscht", ihr: "wascht", wir: "waschen", Sie: "waschen", english: "to wash", Level: "A1", regular: "0", past_participle: "gewaschen", auxiliary_verb: "haben"},
	{ infinitive:"wohnen", ich:"wohne", du: "wohnst", es: "wohnt", ihr: "wohnt", wir: "wohnen", Sie: "wohnen", english: "to live", Level: "A1", regular: "1", past_participle: "gewohnt", auxiliary_verb: "haben"},
	{ infinitive:"abgeben", ich:"gebe ab", du: "gibst ab", es: "gibt ab", ihr: "gebt ab", wir: "geben ab", Sie: "abgeben", english: "to submit", Level: "A2", regular: "0", past_participle: "abgegeben", auxiliary_verb: "haben"},
	{ infinitive:"abschließen", ich:"schließe ab", du: "schließt ab", es: "schließt ab", ihr: "schließt ab", wir: "schließen ab", Sie: "abschließen", english: "to lock", Level: "A2", regular: "0", past_participle: "abgeschlossen", auxiliary_verb: "haben"},
	{ infinitive:"achtgeben", ich:"gebe acht", du: "gibst acht", es: "gibt acht", ihr: "gebt acht", wir: "geben acht", Sie: "achtgeben", english: "to be careful", Level: "C1", regular: "0", past_participle: "achtgegeben", auxiliary_verb: "haben"},
	{ infinitive:"anbieten", ich:"biete an", du: "bietest an", es: "bietet an", ihr: "bietet an", wir: "bieten an", Sie: "anbieten", english: "to offer", Level: "A2", regular: "0", past_participle: "angeboten", auxiliary_verb: "haben"},
	{ infinitive:"anfangen", ich:"fange an", du: "fängst an", es: "fängt an ", ihr: "fangt an", wir: "fangen an", Sie: "anfangen", english: "to begin", Level: "A2", regular: "0", past_participle: "angefangen", auxiliary_verb: "haben"},
	{ infinitive:"anmelden", ich:"melde an", du: "mesdest an", es: "meldet an", ihr: "meldet an", wir: "melden an", Sie: "anmelden", english: "to sign in", Level: "A2", regular: "1", past_participle: "angemeldet", auxiliary_verb: "haben"},
	{ infinitive:"ausgeben", ich:"gebe aus", du: "gibst aus", es: "gibt aus", ihr: "gebt aus", wir: "geben aus", Sie: "ausgeben", english: "to give out", Level: "A2", regular: "0", past_participle: "ausgegeben", auxiliary_verb: "haben"},
	{ infinitive:"ausruhen", ich:"ruhe aus", du: "ruhst aus", es: "ruht aus", ihr: "ruht aus", wir: "ruhen aus", Sie: "ausruhen", english: "to take a rest", Level: "A2", regular: "1", past_participle: "ausgeruht", auxiliary_verb: "haben"},
	{ infinitive:"backen", ich:"backe", du: "bäckst ", es: "bäckt ", ihr: "backt ", wir: "backen", Sie: "backen", english: "to bake", Level: "A2", regular: "1", past_participle: "gebackt", auxiliary_verb: "haben"},
	{ infinitive:"behalten", ich:"behalte", du: "behältst ", es: "behält ", ihr: "behaltet ", wir: "behalten ", Sie: "behalten", english: "to keep", Level: "A2", regular: "0", past_participle: "behalten", auxiliary_verb: "haben"},
	{ infinitive:"einfallen", ich:"falle ein", du: "fällst ein", es: "fällt ein", ihr: "fallt ein", wir: "fallen ein", Sie: "einfallen", english: "to come to mind", Level: "A2", regular: "0", past_participle: "eingefallen", auxiliary_verb: "sein"},
	{ infinitive:"einziehen", ich:"ziehe ein", du: "ziehst ein", es: "zieht ein", ihr: "zieht ein", wir: "ziehen ein", Sie: "einziehen", english: "to move in", Level: "A2", regular: "0", past_participle: "eingezogen", auxiliary_verb: "sein"},
	{ infinitive:"erinnern", ich:"erinnere", du: "erinnerst", es: "erinnert", ihr: "erinnert", wir: "erinnern", Sie: "erinnern", english: "to recall", Level: "A2", regular: "1", past_participle: "erinnern", auxiliary_verb: "haben"},
	{ infinitive:"erlauben", ich:"erlaube", du: "erlaubst", es: "erlaubt", ihr: "erlaubt", wir: "erlauben", Sie: "erlauben", english: "to allow", Level: "A2", regular: "1", past_participle: "erlaubt", auxiliary_verb: "haben"},
	{ infinitive:"fallen", ich:"falle", du: "fällst", es: "fällt", ihr: "fallt", wir: "fallen", Sie: "fallen", english: "to fall", Level: "A2", regular: "0", past_participle: "gefallen", auxiliary_verb: "sein"},
	{ infinitive:"freuen", ich:"freue", du: "freust", es: "freut", ihr: "freut", wir: "freuen", Sie: "freuen", english: "to look forward to", Level: "A2", regular: "1", past_participle: "gefreut", auxiliary_verb: "haben"},
	{ infinitive:"fühlen", ich:"fühle", du: "fühlst", es: "fühlt", ihr: "fühlt", wir: "fühlen", Sie: "fühlen", english: "to feel", Level: "A2", regular: "1", past_participle: "gefühlt", auxiliary_verb: "haben"},
	{ infinitive:"kennenlernen", ich:"lerne kennen", du: "lernst kennen", es: "lernt kennen", ihr: "lernt kennen", wir: "lernen kennen", Sie: "kennenlernen", english: "to get to know", Level: "A2", regular: "1", past_participle: "kennengelernt", auxiliary_verb: "haben"},
	{ infinitive:"herstellen", ich:"stelle her", du: "stellst her", es: "stellt her", ihr: "stellt her", wir: "stellen her", Sie: "herstellen", english: "to produce", Level: "A2", regular: "1", past_participle: "hergestellt", auxiliary_verb: "haben"},
	{ infinitive:"interessieren", ich:"interessiere", du: "interessierst", es: "interessiert", ihr: "interessiert", wir: "interessieren", Sie: "interessieren", english: "to be interested", Level: "A2", regular: "1", past_participle: "interessiert", auxiliary_verb: "haben"},
	{ infinitive:"kriegen", ich:"kriege", du: "kriegst", es: "kriegt", ihr: "kriegt", wir: "kriegen", Sie: "kriegen", english: "to obtain", Level: "A2", regular: "1", past_participle: "gekriegt", auxiliary_verb: "haben"},
	{ infinitive:"lassen", ich:"lasse", du: "lässt ", es: "lässt ", ihr: "lasst ", wir: "lassen", Sie: "lassen", english: "to let", Level: "A2", regular: "0", past_participle: "gelassen", auxiliary_verb: "haben"},
	{ infinitive:"leihen", ich:"leihe", du: "leihst", es: "leiht", ihr: "leiht", wir: "leihen", Sie: "leihen", english: "to lend", Level: "A2", regular: "0", past_participle: "geliehen", auxiliary_verb: "haben"},
	{ infinitive:"liefern", ich:"liefere", du: "lieferst", es: "liefert", ihr: "liefert", wir: "liefern", Sie: "liefern", english: "to deliver", Level: "A2", regular: "1", past_participle: "geliefert", auxiliary_verb: "haben"},
	{ infinitive:"merken", ich:"merke", du: "merkst", es: "merkt", ihr: "merkt", wir: "merken", Sie: "merken", english: "to notice", Level: "A2", regular: "1", past_participle: "gemerkt", auxiliary_verb: "haben"},
	{ infinitive:"mitnehmen", ich:"nehme mit", du: "nimmst mit", es: "nimmt mit", ihr: "nehmt mit", wir: "nehmen mit", Sie: "mitnehmen", english: "to take with", Level: "A2", regular: "0", past_participle: "mitgenommen", auxiliary_verb: "haben"},
	{ infinitive:"riechen", ich:"rieche", du: "riechst", es: "riecht", ihr: "riecht", wir: "riechen", Sie: "riechen", english: "to allow", Level: "A2", regular: "0", past_participle: "gerochen", auxiliary_verb: "haben"},
	{ infinitive:"sammeln", ich:"sammele", du: "sammelst", es: "sammelt", ihr: "sammelt", wir: "sammeln", Sie: "sammeln", english: "to collect", Level: "A2", regular: "1", past_participle: "gesammelt", auxiliary_verb: "haben"},
	{ infinitive:"schenken", ich:"schenke", du: "schenkst", es: "schenkt", ihr: "schenkt", wir: "schenken", Sie: "schenken", english: "to give", Level: "A1", regular: "1", past_participle: "geschenkt", auxiliary_verb: "haben"},
	{ infinitive:"sparen", ich:"spare", du: "sparst", es: "spart", ihr: "spart", wir: "sparen", Sie: "sparen", english: "to save up", Level: "A2", regular: "1", past_participle: "gespart", auxiliary_verb: "haben"},
	{ infinitive:"speichern", ich:"speichern", du: "speichst", es: "spiechere", ihr: "speichert", wir: "speichern", Sie: "speichern", english: "to save", Level: "A2", regular: "1", past_participle: "gespeichert", auxiliary_verb: "haben"},
	{ infinitive:"stecken", ich:"stecke", du: "steckst", es: "steckt", ihr: "steckt", wir: "stecken", Sie: "stecken", english: "to plug", Level: "A2", regular: "1", past_participle: "gesteckt", auxiliary_verb: "haben"},
	{ infinitive:"stören", ich:"störe", du: "störst", es: "stört", ihr: "stört", wir: "stören", Sie: "stören", english: "to disturb", Level: "A2", regular: "1", past_participle: "gestört", auxiliary_verb: "haben"},
	{ infinitive:"streiten", ich:"streite", du: "streitest", es: "streitet", ihr: "streitet", wir: "streiten", Sie: "streiten", english: "to fight", Level: "A2", regular: "0", past_participle: "gestritten", auxiliary_verb: "haben"},
	{ infinitive:"tanken", ich:"tanke", du: "tankst", es: "tankt", ihr: "tankt", wir: "tanken", Sie: "tanken", english: "to refuel", Level: "B1", regular: "1", past_participle: "getankt", auxiliary_verb: "haben"},
	{ infinitive:"teilnehmen", ich:"nehme teil", du: "nimmst teil", es: "nimmt teil", ihr: "nehmt teil", wir: "nehmen teil", Sie: "teilnehmen", english: "to take part", Level: "A2", regular: "0", past_participle: "teilgenommen", auxiliary_verb: "haben"},
	{ infinitive:"umziehen", ich:"ziehe um", du: "ziehst um", es: "zieht um", ihr: "zieht  um", wir: "ziehen um", Sie: "umziehen", english: "to move", Level: "A2", regular: "0", past_participle: "umgezogen", auxiliary_verb: "sein"},
	{ infinitive:"unterhalten", ich:"unterhalte", du: "unterhältst", es: "unterhält ", ihr: "unterhaltet ", wir: "unterhalten ", Sie: "unterhalten", english: "to chat", Level: "A2", regular: "0", past_participle: "unterhalten", auxiliary_verb: "haben"},
	{ infinitive:"unternehmen", ich:"unternehme", du: "unternimmst ", es: "unternimmt ", ihr: "unternehmt", wir: "unternehmen ", Sie: "unternehmen", english: "to undertake", Level: "A2", regular: "0", past_participle: "untergenommen", auxiliary_verb: "haben"},
	{ infinitive:"verlängern", ich:"verlänge", du: "verlängerst ", es: "verlängert ", ihr: "verlängert ", wir: "verlängern", Sie: "verlängern", english: "to extend", Level: "A2", regular: "1", past_participle: "verlängert ", auxiliary_verb: "haben"},
	{ infinitive:"verpassen", ich:"verpasse", du: "verpasst ", es: "verpasst ", ihr: "verpasst ", wir: "verpassen", Sie: "verpassen", english: "to miss", Level: "A2", regular: "1", past_participle: "verpasst", auxiliary_verb: "haben"},
	{ infinitive:"vereinbaren", ich:"vereinbare", du: "vereinbarst", es: "vereinbart ", ihr: "vereinbart ", wir: "vereinbaren ", Sie: "vereinbaren", english: "to arrange", Level: "A2", regular: "1", past_participle: "vereinbart", auxiliary_verb: "haben"},
	{ infinitive:"verletzen", ich:"verletze", du: "verletzt ", es: "verletzt ", ihr: "verletzt ", wir: "verletzen", Sie: "verletzen", english: "to harm", Level: "A2", regular: "1", past_participle: "verletzt", auxiliary_verb: "haben"},
	{ infinitive:"verlieren", ich:"verliere", du: "verlierst ", es: "verliert ", ihr: "verliert ", wir: "verlieren ", Sie: "verlieren", english: "to lose something", Level: "A2", regular: "0", past_participle: "verloren", auxiliary_verb: "haben"},
	{ infinitive:"verschieben", ich:"verschiebe", du: "verschiebst ", es: "verschiebt ", ihr: "verschiebt ", wir: "verschieben ", Sie: "verschieben", english: "to move", Level: "A2", regular: "0", past_participle: "verschoben", auxiliary_verb: "haben"},
	{ infinitive:"wählen", ich:"wähle", du: "wählst ", es: "wählt ", ihr: "wählt ", wir: "wählen ", Sie: "wählen", english: "to choose", Level: "A2", regular: "1", past_participle: "wählen", auxiliary_verb: "haben"},
	{ infinitive:"wünschen", ich:"wünsche", du: "wünschst", es: "wünscht ", ihr: "wünscht ", wir: "wünschen", Sie: "wünschen", english: "to wish", Level: "A2", regular: "1", past_participle: "wünschen", auxiliary_verb: "haben"}
]


VERBS.each do | verb |
	v = Verb.find_or_initialize_by( infinitive: verb[:infinitive])
	level = LanguageLevel.find_by!(level_code: verb[:Level])
	v.language_level=level
	v.english = verb[:english]
	v.auxiliary_verb = verb[:auxiliary_verb]
	v.regular = verb[:regular]
	v.save!

	[:ich, :du, :es, :ihr, :wir, :Sie].each do | subject |
		vf = v.verb_forms.find_or_initialize_by( form: 'present', subject: subject)
		vf.word = verb[subject]
		vf.save
	end
	vf = v.verb_forms.find_or_initialize_by( form: 'past_participle' )
	vf.word = verb[:past_participle]
	vf.save!
end
