# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

Gender.create!(char_desc: 'm', desc: 'Masculine') 
Gender.create!(char_desc: 'f', desc: 'Feminine') 
Gender.create!(char_desc: 'n', desc: 'Neutral') 

LanguageLevel.create!(level_code: 'A1')
LanguageLevel.create!(level_code: 'A2')
LanguageLevel.create!(level_code: 'B1')
LanguageLevel.create!(level_code: 'B2')
LanguageLevel.create!(level_code: 'C1')

Game.create!(game_code: 'falling_text', score_code_pattern: '#topicId_#levelId', game_title: 'Falling Text', game_short_desc: 'Practice your german with a falling text game.',
	game_desc: 'Shoot down the words as they appear, by typing the answer before they hit the blocks. When all the blocks are smashed the game is over!' /
	'  Score extra points by shooting down the bonus words that fly horizontally across the screen. With each level progression, you will score more points,' / 
	' so try to protect your blocks as long as possible to achieve the highest scores!. You can choose between practising vocabulary or conjugation.' / 
	' For Vocabulary the text displayed will be in English, type in the German translation to shoot the word down. For conjugation practice, ' /
	'a verb will be displayed in the infinitive, type it in the corresponding conjugated form to shoot the words.'
)

NOUNS = [{ gender:"m", word: "Abend", english: "evening", level: "A1"},
{ gender:"n", word: "Abendbrot", english: "evening meal", level: "A2"},
{ gender:"n", word: "Angebot", english: "offer / deal", level: "A1"},
{ gender:"f", word: "Adresse", english: "address", level: "A1"},
{ gender:"f", word: "Abfahrt", english: "departure", level: "A1"},
{ gender:"m", word: "Abfall", english: "Trash", level: "A1"},
{ gender:"f", word: "Ampel", english: "traffic lights", level: "A1"},
{ gender:"m", word: "Apfel", english: "apple", level: "A1"},
{ gender:"f", word: "Apotheke", english: "pharmacy", level: "A1"},
{ gender:"m", word: "Arzt", english: "Doctor (male)", level: "A1"},
{ gender:"f", word: "Arbeit", english: "work", level: "A1"},
{ gender:"f", word: "Aufgabe", english: "exercise", level: "A1"},
{ gender:"m", word: "Aufschnitt", english: "cold sliced meat", level: "A1"},
{ gender:"n", word: "Auge", english: "eye", level: "A1"},
{ gender:"n", word: "Ausland", english: "overseas/abroad", level: "A1"},
{ gender:"f", word: "Aussicht", english: "view", level: "A1"},
{ gender:"m", word: "Arm", english: "poor/poverty", level: "A2"},
{ gender:"n", word: "Auto", english: "car", level: "A1"},
{ gender:"f", word: "Bäckerei", english: "bakery", level: "A1"},
{ gender:"n", word: "Bad", english: "bath", level: "A1"},
{ gender:"n", word: "Baby", english: "baby", level: "A1"},
{ gender:"m", word: "Bahnhof", english: "(train,bus) station", level: "A1"},
{ gender:"n", word: "Bank", english: "Bank", level: "A1"},
{ gender:"m", word: "Bauch", english: "stomach", level: "A1"},
{ gender:"m", word: "Baum", english: "tree", level: "A1"},
{ gender:"n", word: "Bein", english: "leg", level: "A1"},
{ gender:"m", word: "Berg", english: "mountain", level: "A1"},
{ gender:"n", word: "Bett", english: "bed", level: "A1"},
{ gender:"m", word: "Beruf", english: "Job", level: "A1"},
{ gender:"n", word: "Bier", english: "beer", level: "A1"},
{ gender:"n", word: "Bild", english: "picture", level: "A1"},
{ gender:"f", word: "Blume", english: "flower", level: "A1"},
{ gender:"n", word: "Boot", english: "boat", level: "A1"},
{ gender:"m", word: "Brief", english: "letter", level: "A1"},
{ gender:"f", word: "Brille", english: "pair of glasses", level: "A1"},
{ gender:"n", word: "Birne", english: "pear", level: "A1"},
{ gender:"n", word: "Brot", english: "bread", level: "A1"},
{ gender:"n", word: "Brötchen", english: "bread roll", level: "A1"},
{ gender:"f", word: "Brücke", english: "bridge", level: "A1"},
{ gender:"m", word: "Bruder", english: "brother", level: "A1"},
{ gender:"n", word: "Buch", english: "book", level: "A1"},
{ gender:"f", word: "Burg", english: "castle/ fortress", level: "A1"},
{ gender:"n", word: "Büro", english: "office", level: "A1"},
{ gender:"m", word: "Campingplatz", english: "camping ground", level: "A1"},
{ gender:"m", word: "Cousin", english: "Cousin (male)", level: "A2"},
{ gender:"f", word: "Cousine", english: "Cousin (female)", level: "A2"},
{ gender:"m", word: "Direktor", english: "principal (male)", level: "A2"},
{ gender:"f", word: "Directorin", english: "principal (female)", level: "A2"},
{ gender:"m", word: "Dom", english: "cathedral", level: "A1"},
{ gender:"n", word: "Dorf", english: "village", level: "A1"},
{ gender:"f", word: "Ecke", english: "corner", level: "A1"},
{ gender:"n", word: "Ei", english: "egg", level: "A1"},
{ gender:"m", word: "Einwohner", english: "inhabitant", level: "A2"},
{ gender:"n", word: "Einzelkind", english: "only child", level: "A2"},
{ gender:"n", word: "Eis", english: "ice, icecream", level: "A1"},
{ gender:"f", word: "Eltern", english: "parents", level: "A1"},
{ gender:"n", word: "Erdgeschoss", english: "ground floor", level: "A1"},
{ gender:"m", word: "Erwachsene", english: "adult (male)", level: "A1"},
{ gender:"f", word: "Erwachsene", english: "adult (female)", level: "A1"},
{ gender:"m", word: "Euro", english: "Euro", level: "A1"},
{ gender:"n", word: "Fach", english: "Subject ( at school)", level: "A2"},
{ gender:"n", word: "Fahrrad", english: "bicycle", level: "A1"},
{ gender:"f", word: "Familie", english: "family", level: "A1"},
{ gender:"f", word: "Farbe", english: "colour", level: "A1"},
{ gender:"m", word: "Fehler", english: "mistake", level: "A1"},
{ gender:"n", word: "Fenster", english: "window", level: "A1"},
{ gender:"f", word: "Ferien", english: "holidays", level: "A1"},
{ gender:"m", word: "Fernseher", english: "television", level: "A1"},
{ gender:"n", word: "Fest", english: "festival", level: "A1"},
{ gender:"n", word: "Fieber", english: "fever", level: "A2"},
{ gender:"f", word: "Figur", english: "figure", level: "A2"},
{ gender:"f", word: "Flasche", english: "bottle", level: "A1"},
{ gender:"n", word: "Fleisch", english: "meat", level: "A1"},
{ gender:"m", word: "Flughafen", english: "airport", level: "A1"},
{ gender:"n", word: "Flugzeug", english: "plane", level: "A1"},
{ gender:"m", word: "Fluss", english: "river", level: "A1"},
{ gender:"f", word: "Frau", english: "woman/wife/Mrs", level: "A1"},
{ gender:"f", word: "Fremdsprache", english: "foreign language", level: "A2"},
{ gender:"m", word: "Freund", english: "boyfriend", level: "A1"},
{ gender:"f", word: "Freundin", english: "girlfriend", level: "A1"},
{ gender:"m", word: "Führerschein", english: "driver's licence", level: "A2"},
{ gender:"m", word: "Fuß", english: "foot", level: "A1"},
{ gender:"m", word: "Fußball", english: "football", level: "A1"},
{ gender:"m", word: "Garten", english: "garden", level: "A1"},
{ gender:"m", word: "Gast", english: "guest", level: "A1"},
{ gender:"n", word: "Gebäude", english: "building", level: "A1"},
{ gender:"m", word: "Geburtstag", english: "birthday", level: "A1"},
{ gender:"n", word: "Geld", english: "money", level: "A1"},
{ gender:"n", word: "Gemüse", english: "vegetables", level: "A1"},
{ gender:"n", word: "Geschäft", english: "shop/business", level: "A1"},
{ gender:"n", word: "Geschenk", english: "present", level: "A1"},
{ gender:"f", word: "Geschichte", english: "history/story", level: "A2"},
{ gender:"f", word: "Geschwister", english: "siblings", level: "A2"},
{ gender:"n", word: "Gesicht", english: "face", level: "A1"},
{ gender:"n", word: "Gleis", english: "track/platform", level: "A2"},
{ gender:"m", word: "Grad", english: "degrees", level: "A1"},
{ gender:"f", word: "Großmutter", english: "grandmother", level: "A1"},
{ gender:"m", word: "Großvater", english: "grandfather", level: "A1"},
{ gender:"f", word: "Groβeltern", english: "grandparents", level: "A1"},
{ gender:"f", word: "Grundschule", english: "primary school", level: "A2"},
{ gender:"n", word: "Gymnasium", english: "academic high school", level: "A2"},
{ gender:"f", word: "Haare", english: "hair", level: "A1"},
{ gender:"m", word: "Hafen", english: "harbour", level: "A2"},
{ gender:"m", word: "Hals", english: "neck/throat", level: "A2"},
{ gender:"f", word: "Haltestelle", english: "(bus,tram) stop", level: "A2"},
{ gender:"n", word: "Handy", english: "mobile phone", level: "A1"},
{ gender:"f", word: "Hauptstadt", english: "capital city", level: "A1"},
{ gender:"n", word: "Haus", english: "house", level: "A1"},
{ gender:"f", word: "Hausaufgaben", english: "homework", level: "A1"},
{ gender:"n", word: "Haustier", english: "pet", level: "A1"},
{ gender:"n", word: "Heft", english: "exercise book", level: "A2"},
{ gender:"n", word: "Hemd", english: "shirt", level: "A1"},
{ gender:"m", word: "Herr", english: "gentleman/ Mr", level: "A1"},
{ gender:"f", word: "Hose", english: "pair of pants/trousers", level: "A1"},
{ gender:"m", word: "Hund", english: "dog", level: "A1"},
{ gender:"f", word: "Insel", english: "island", level: "A1"},
{ gender:"f", word: "Jacke", english: "jacket", level: "A1"},
{ gender:"n", word: "Jahr", english: "year", level: "A1"},
{ gender:"f", word: "Jahreszeit", english: "season", level: "A1"},
{ gender:"m", word: "Junge", english: "boy", level: "A1"},
{ gender:"m", word: "Kaffee", english: "coffee", level: "A1"},
{ gender:"f", word: "Karte", english: "card/ticket/map", level: "A1"},
{ gender:"f", word: "Kartoffeln", english: "potatoes", level: "A1"},
{ gender:"m", word: "Käse", english: "cheese", level: "A1"},
{ gender:"f", word: "Kasse", english: "checkout,till", level: "A1"},
{ gender:"f", word: "Katze", english: "cat", level: "A1"},
{ gender:"n", word: "Kaufhaus", english: "department store", level: "A2"},
{ gender:"m", word: "Keller", english: "cellar", level: "A1"},
{ gender:"f", word: "Kerze", english: "candle", level: "A1"},
{ gender:"n", word: "Kind", english: "child", level: "A1"},
{ gender:"f", word: "Kirche", english: "church", level: "A1"},
{ gender:"f", word: "Klamotten", english: "clothoes", level: "A1"},
{ gender:"f", word: "Klasse", english: "class", level: "A2"},
{ gender:"n", word: "Kleid", english: "dress", level: "A1"},
{ gender:"f", word: "Kneipe", english: "pub", level: "A1"},
{ gender:"m", word: "Koffer", english: "suitcase", level: "A1"},
{ gender:"m", word: "Kopf", english: "head", level: "A1"},
{ gender:"f", word: "Küche", english: "kitchen", level: "A1"},
{ gender:"m", word: "Kuchen", english: "cake", level: "A1"},
{ gender:"f", word: "Kuh", english: "cow", level: "A2"},
{ gender:"m", word: "Kühlschrank", english: "fridge", level: "A1"},
{ gender:"f", word: "Kunst", english: "art", level: "A1"},
{ gender:"f", word: "Küste", english: "coast", level: "A2"},
{ gender:"n", word: "Land", english: "Country/state", level: "A1"},
{ gender:"f", word: "Landschaft", english: "scenery, landscape", level: "A2"},
{ gender:"m", word: "Lärm", english: "noise", level: "A2"},
{ gender:"m", word: "Lehrer", english: "teacher (male)", level: "A1"},
{ gender:"f", word: "Leherin", english: "teacher (female)", level: "A1"},
{ gender:"f", word: "Leute", english: "people", level: "A1"},
{ gender:"n", word: "Mädchen", english: "girl", level: "A1"},
{ gender:"m", word: "Mann", english: "man,husband", level: "A1"},
{ gender:"m", word: "Mantel", english: "coat", level: "A1"},
{ gender:"m", word: "Markt", english: "market", level: "A1"},
{ gender:"f", word: "Mauer", english: "wall (outside)", level: "A2"},
{ gender:"f", word: "Maus", english: "mouse", level: "A2"},
{ gender:"n", word: "Meer", english: "sea", level: "A2"},
{ gender:"m", word: "Mensch", english: "person", level: "A1"},
{ gender:"f", word: "Milch", english: "milk", level: "A1"},
{ gender:"f", word: "Mitternacht", english: "midnight", level: "A1"},
{ gender:"m", word: "Mittag", english: "noon", level: "A1"},
{ gender:"n", word: "Mittagessen", english: "lunch", level: "A1"},
{ gender:"f", word: "Möbel", english: "furniture", level: "A1"},
{ gender:"m", word: "Monat", english: "month", level: "A1"},
{ gender:"m", word: "Morgen", english: "morning", level: "A1"},
{ gender:"m", word: "Mund", english: "mouth", level: "A1"},
{ gender:"f", word: "Mutter", english: "mother", level: "A1"},
{ gender:"m", word: "Nachbar", english: "neighbour", level: "A1"},
{ gender:"m", word: "Nachmittag", english: "afternoon", level: "A1"},
{ gender:"f", word: "Nachrichten", english: "news", level: "A2"},
{ gender:"f", word: "Nacht", english: "night", level: "A1"},
{ gender:"m", word: "Nachtisch", english: "dessert", level: "A1"},
{ gender:"f", word: "Nase", english: "nose", level: "A1"},
{ gender:"f", word: "Naturwissenschaften", english: "science", level: "A2"},
{ gender:"f", word: "Nordsee", english: "North Sea", level: "A2"},
{ gender:"f", word: "Note", english: "mark (school)/musical note", level: "A2"},
{ gender:"f", word: "Nudeln", english: "pasta/noodles", level: "A2"},
{ gender:"f", word: "Nummer", english: "number", level: "A1"},
{ gender:"n", word: "Ohr", english: "ear", level: "A1"},
{ gender:"m", word: "Onkel", english: "uncle", level: "A1"},
{ gender:"m", word: "Ort", english: "place", level: "A1"},
{ gender:"n", word: "Obst", english: "fruit", level: "A1"},
{ gender:"n", word: "Paar", english: "pair/couple", level: "A2"},
{ gender:"n", word: "Paket", english: "parcel", level: "A1"},
{ gender:"n", word: "Papier", english: "paper", level: "A1"},
{ gender:"f", word: "Pause", english: "interval/break", level: "A1"},
{ gender:"n", word: "Pferd", english: "horse", level: "A1"},
{ gender:"m", word: "Platz", english: "place", level: "A1"},
{ gender:"f", word: "Polizei", english: "police", level: "A1"},
{ gender:"f", word: "Prüfung", english: "exam, fries", level: "A2"},
{ gender:"n", word: "Rathaus", english: "town hall", level: "A1"},
{ gender:"f", word: "Richtung", english: "direction", level: "A2"},
{ gender:"m", word: "Rock", english: "skirt", level: "A1"},
{ gender:"m", word: "Rücken", english: "back", level: "A1"},
{ gender:"f", word: "Sache", english: "thing", level: "A2"},
{ gender:"m", word: "Saft", english: "juice", level: "A1"},
{ gender:"m", word: "Salat", english: "lettuce,salad", level: "A1"},
{ gender:"n", word: "Schaf", english: "sheep", level: "A2"},
{ gender:"m", word: "Schinken", english: "ham", level: "A2"},
{ gender:"n", word: "Schlafzimmer", english: "bedroom", level: "A1"},
{ gender:"n", word: "Schloss", english: "castle", level: "A1"},
{ gender:"f", word: "Schmerzen", english: "pain", level: "A1"},
{ gender:"m", word: "Schnupfen", english: "cold (illness)", level: "A2"},
{ gender:"f", word: "Schokolade", english: "chocolate", level: "A1"},
{ gender:"m", word: "Schrank", english: "cupboard", level: "A1"},
{ gender:"m", word: "Schuh", english: "shoe", level: "A1"},
{ gender:"f", word: "Schule", english: "school", level: "A1"},
{ gender:"m", word: "Schüler", english: "school student (male)", level: "A1"},
{ gender:"f", word: "Schülerin", english: "school student (female)", level: "A1"},
{ gender:"m", word: "Schlüssel", english: "key", level: "A1"},
{ gender:"f", word: "Schweiz", english: "Switzerland", level: "A2"},
{ gender:"f", word: "Schwester", english: "sister", level: "A1"},
{ gender:"n", word: "Schwimmbad", english: "swimming pool", level: "A1"},
{ gender:"m", word: "See", english: "lake", level: "A1"},
{ gender:"f", word: "Sehenswürdigkeiten", english: "tourist sites", level: "A2"},
{ gender:"f", word: "Seite", english: "side,page", level: "A2"},
{ gender:"m", word: "Senf", english: "mustard", level: "A2"},
{ gender:"m", word: "Sommer", english: "summer", level: "A1"},
{ gender:"f", word: "Sonne", english: "sun", level: "A1"},
{ gender:"m", word: "Sonnenbrand", english: "sunburn", level: "A1"},
{ gender:"f", word: "Stadt", english: "town,city", level: "A1"},
{ gender:"m", word: "Strift", english: "pen", level: "A2"},
{ gender:"f", word: "Stiefmutter", english: "stepmother", level: "A2"},
{ gender:"m", word: "Stiefvater", english: "stepfather", level: "A2"},
{ gender:"m", word: "Strand", english: "beach", level: "A1"},
{ gender:"f", word: "Straße", english: "street", level: "A1"},
{ gender:"f", word: "Straßenbahn", english: "tram", level: "A1"},
{ gender:"n", word: "Stück", english: "piece", level: "A1"},
{ gender:"m", word: "Stuhl", english: "chair", level: "A1"},
{ gender:"f", word: "Stunde", english: "hour", level: "A1"},
{ gender:"m", word: "Supermarkt", english: "supermarket", level: "A1"},
{ gender:"f", word: "Suppe", english: "soup", level: "A1"},
{ gender:"f", word: "Süβigkeiten", english: "sweets,lollies", level: "A2"},
{ gender:"m", word: "Tag", english: "day", level: "A1"},
{ gender:"n", word: "Tal", english: "valley", level: "B1"},
{ gender:"f", word: "Tante", english: "aunt", level: "A1"},
{ gender:"f", word: "Tasche", english: "bag,pocket", level: "A1"},
{ gender:"f", word: "Tasse", english: "cup", level: "A2"},
{ gender:"m", word: "Tee", english: "tea", level: "A1"},
{ gender:"m", word: "Teil", english: "part", level: "A2"},
{ gender:"m", word: "Teppich", english: "carpet", level: "A2"},
{ gender:"m", word: "Termin", english: "appointment", level: "A1"},
{ gender:"n", word: "Theater", english: "theatre", level: "A1"},
{ gender:"n", word: "Tier", english: "animal", level: "A1"},
{ gender:"m", word: "Tisch", english: "table", level: "A1"},
{ gender:"f", word: "Treppe", english: "stairs", level: "A1"},
{ gender:"f", word: "Tür", english: "door", level: "A1"},
{ gender:"f", word: "Tüte", english: "bag (shopping)", level: "A1"},
{ gender:"f", word: "Uhr", english: "clock", level: "A1"},
{ gender:"m", word: "Unterricht", english: "lesson/class", level: "A1"},
{ gender:"m", word: "Urlaub", english: "holiday", level: "A1"},
{ gender:"m", word: "Vater", english: "father", level: "A1"},
{ gender:"m", word: "Vogel", english: "bird", level: "A1"},
{ gender:"m", word: "Vormittag", english: "morning", level: "A2"},
{ gender:"m", word: "Vorname", english: "first name", level: "A1"},
{ gender:"m", word: "Wald", english: "forest", level: "A1"},
{ gender:"f", word: "Wand", english: "wall (inside)", level: "A1"},
{ gender:"n", word: "Wasser", english: "water", level: "A1"},
{ gender:"m", word: "Weg", english: "path", level: "A1"},
{ gender:"m", word: "Wein", english: "wine", level: "A1"},
{ gender:"f", word: "Welt", english: "world", level: "A1"},
{ gender:"n", word: "Wetter", english: "weather", level: "A1"},
{ gender:"f", word: "Woche", english: "week", level: "A1"},
{ gender:"n", word: "Wochenende", english: "weekend", level: "A1"},
{ gender:"f", word: "Wohnung", english: "flat,apartment", level: "A1"},
{ gender:"n", word: "Wort", english: "word", level: "A1"},
{ gender:"f", word: "Wurst", english: "sausage", level: "A2"},
{ gender:"f", word: "Zeit", english: "time", level: "A1"},
{ gender:"f", word: "Zeitung", english: "newspaper", level: "A1"},
{ gender:"n", word: "Zelt", english: "tent", level: "A2"},
{ gender:"n", word: "Zeugnis", english: "school report", level: "A2"},
{ gender:"n", word: "Zimmer", english: "room", level: "A1"},
{ gender:"m", word: "Zug", english: "train", level: "A2"},
{ gender:"m", word: "Montag", english: "Monday", level: "A1"},
{ gender:"m", word: "Dienstag", english: "Tuesday", level: "A1"},
{ gender:"m", word: "Mittwoch", english: "Wednesday", level: "A1"},
{ gender:"m", word: "Donnerstag", english: "Thursday", level: "A1"},
{ gender:"m", word: "Freitag", english: "Friday", level: "A1"},
{ gender:"m", word: "Samstag", english: "Saturday", level: "A1"},
{ gender:"m", word: "Sonntag", english: "Sunday", level: "A1"},
{ gender:"m", word: "Januar", english: "January", level: "A1"},
{ gender:"m", word: "Februar", english: "February", level: "A1"},
{ gender:"m", word: "März ", english: "March", level: "A1"},
{ gender:"m", word: "April", english: "April", level: "A1"},
{ gender:"m", word: "Mai", english: "May", level: "A1"},
{ gender:"m", word: "Juni", english: "June", level: "A1"},
{ gender:"m", word: "Juli", english: "July", level: "A1"},
{ gender:"m", word: "August", english: "August", level: "A1"},
{ gender:"m", word: "September", english: "September", level: "A1"},
{ gender:"m", word: "Oktober", english: "October", level: "A1"},
{ gender:"m", word: "November", english: "November", level: "A1"},
{ gender:"m", word: "Dezember", english: "December", level: "A1"},
{ gender:"m", word: "Fruhling", english: "Spring", level: "A1"},
{ gender:"m", word: "Sommer", english: "Summer", level: "A1"},
{ gender:"m", word: "Herbst", english: "Autumn", level: "A1"},
{ gender:"m", word: "Winter", english: "Winter", level: "A1"},
{ gender:"m", word: "Anzug", english: "Suit", level: "A2"},
{ gender:"m", word: "Angestellte", english: "Employees", level: "A2"},
{ gender:"m", word: "Arbeiter", english: "worker", level: "A2"},
{ gender:"m", word: "Ärger", english: "trouble", level: "A2"},
{ gender:"m", word: "Aufzug", english: "elevator", level: "A2"},
{ gender:"m", word: "Ausgang", english: "exit", level: "A2"},
{ gender:"f", word: "Ausstellung", english: "exhibition", level: "A2"},
{ gender:"m", word: "Ausweis", english: "ID card", level: "A2"},
{ gender:"f", word: "Bahn", english: "track/lane/railway", level: "A2"},
{ gender:"m", word: "Bauch", english: "stomach", level: "A2"},
{ gender:"m", word: "Berg", english: "mountain", level: "A2"},
{ gender:"m", word: "Beweber", english: "Applicants", level: "A2"},
{ gender:"n", word: "Blatt", english: "Leaf / sheet", level: "A2"},
{ gender:"f", word: "Bluse", english: "blouse", level: "A2"},
{ gender:"n", word: "Blut", english: "blood", level: "A2"},
{ gender:"f", word: "Bohne", english: "bean (food)", level: "A2"},
{ gender:"m", word: "Briefkasten", english: "Mailbox", level: "A2"},
{ gender:"m", word: "Briefumslag", english: "Envelope", level: "A2"},
{ gender:"n", word: "Dach", english: "roof", level: "A2"},
{ gender:"f", word: "Dauer", english: "duration", level: "A2"},
{ gender:"f", word: "Dose", english: "tin can", level: "A2"},
{ gender:"f", word: "Dusche", english: "shower", level: "A2"},
{ gender:"f", word: "Ehefrau", english: "wife", level: "A2"},
{ gender:"m", word: "Enklekind", english: "grandchild", level: "A2"},
{ gender:"n", word: "Erdgeschloss", english: "ground floor", level: "A2"},
{ gender:"f", word: "Erfahrung", english: "experience", level: "A2"},
{ gender:"f", word: "Erlaubnis", english: "permission", level: "A2"},
{ gender:"f", word: "Fabrik", english: "factory", level: "A2"},
{ gender:"f", word: "Fähre", english: "ferry", level: "A2"},
{ gender:"m", word: "Fahrplan", english: "timetable", level: "A2"},
{ gender:"f", word: "Farbe", english: "colour", level: "A2"},
{ gender:"m", word: "Fehler", english: "mistake", level: "A2"},
{ gender:"m", word: "Feiertag", english: "public holiday", level: "A2"},
{ gender:"n", word: "Fest", english: "festival", level: "A2"},
{ gender:"n", word: "Feuer", english: "fire", level: "A2"},
{ gender:"m", word: "Flur", english: "Hall / corridor", level: "A2"},
{ gender:"m", word: "Fluss", english: "river", level: "A2"},
{ gender:"m", word: "Frisör", english: "hairdresser", level: "A2"},
{ gender:"f", word: "Frist", english: "Deadline ", level: "A2"},
{ gender:"f", word: "Garantie", english: "guarantee", level: "A2"},
{ gender:"m", word: "Gast", english: "guest", level: "A2"},
{ gender:"f", word: "Gebühr", english: "Fee / charge", level: "A2"},
{ gender:"n", word: "Geburtsjahr", english: "birth year", level: "A2"},
{ gender:"n", word: "Gegenteil", english: "opposite", level: "A2"},
{ gender:"n", word: "Gericht", english: "dish (food)", level: "A2"},
{ gender:"f", word: "Gesundheit", english: "health", level: "A2"},
{ gender:"m", word: "Glückwunsch", english: "congratulation", level: "A2"},
{ gender:"f", word: "Grenze", english: "border", level: "A2"},
{ gender:"f", word: "Heimat", english: "homeland", level: "A2"},
{ gender:"f", word: "Heizung", english: "heater", level: "A2"},
{ gender:"n", word: "Hemd", english: "shirt", level: "A2"},
{ gender:"n", word: "Herz", english: "heart", level: "A2"},
{ gender:"f", word: "Hochzeit", english: "wedding", level: "A2"},
{ gender:"n", word: "Holz", english: "Wood", level: "A2"},
{ gender:"f", word: "Hose", english: "Pants", level: "A2"},
{ gender:"m", word: "Inhalt", english: "content", level: "A2"},
{ gender:"m", word: "Kalander", english: "calender", level: "A2"},
{ gender:"f", word: "Kanne", english: "Jug", level: "A2"},
{ gender:"f", word: "Kette", english: "chain", level: "A2"},
{ gender:"n", word: "Kino", english: "cinema", level: "A2"},
{ gender:"n", word: "Konto", english: "account", level: "A2"},
{ gender:"f", word: "Krankheit", english: "illness", level: "A2"},
{ gender:"m", word: "Kredit", english: "credit", level: "A2"},
{ gender:"m", word: "Kreis", english: "circle", level: "A2"},
{ gender:"f", word: "Kundigung", english: "Termination", level: "A2"},
{ gender:"m", word: "Laden", english: "shop/store", level: "A2"},
{ gender:"n", word: "Lager", english: "stock/warehouse", level: "A2"},
{ gender:"f", word: "Landschaft", english: "landscape/countryside", level: "A2"},
{ gender:"m", word: "Lohn", english: "wage/salary", level: "A2"},
{ gender:"n", word: "Mal", english: "Times", level: "A2"},
{ gender:"m", word: "Markt", english: "market", level: "A2"},
{ gender:"f", word: "Menge", english: "amount/quantity", level: "A2"},
{ gender:"n", word: "Metall", english: "Metal", level: "A2"},
{ gender:"f", word: "Million", english: "million", level: "A2"},
{ gender:"f", word: "Mitte", english: "center", level: "A2"},
{ gender:"f", word: "Mode", english: "Fashion", level: "A2"},
{ gender:"m", word: "Motor", english: "Motor", level: "A2"},
{ gender:"m", word: "Müll", english: "Trash", level: "A2"},
{ gender:"m", word: "Mund", english: "Mouth", level: "A2"},
{ gender:"f", word: "Nachrichten", english: "News", level: "A2"},
{ gender:"f", word: "Natur", english: "Nature", level: "A2"},
{ gender:"m", word: "Nebel", english: "Fog", level: "A2"},
{ gender:"n", word: "Plastik", english: "Plastic", level: "A2"},
{ gender:"n", word: "Prozent", english: "Percent", level: "A2"},
{ gender:"m", word: "Raucher", english: "Smoker", level: "A2"},
{ gender:"f", word: "Reinigung", english: "Cleaning", level: "A2"},
{ gender:"n", word: "Rind", english: "Beef", level: "A2"},
{ gender:"m", word: "Rücken", english: "back/spine", level: "A2"},
{ gender:"f", word: "Sache", english: "thing", level: "A2"},
{ gender:"n", word: "Schloss", english: "palace/castle", level: "A2"},
{ gender:"m", word: "Schnee", english: "snow", level: "A2"},
{ gender:"f", word: "Seife", english: "soap", level: "A2"},
{ gender:"f", word: "Sorge", english: "worry/concern", level: "A2"},
{ gender:"m", word: "Spaβ", english: "fun", level: "A2"},
{ gender:"f", word: "Spülmaschine", english: "dishwasher", level: "A2"},
{ gender:"f", word: "Stelle", english: "Job", level: "A2"},
{ gender:"m", word: "Strand", english: "beach", level: "A2"},
{ gender:"n", word: "Streichholz", english: "match stick", level: "A2"},
{ gender:"m", word: "Vermieter", english: "landlord/lessor", level: "A2"},
{ gender:"m", word: "Verein", english: "club", level: "A2"},
{ gender:"f", word: "Verbindung", english: "connection", level: "A2"},
{ gender:"f", word: "Versicherung", english: "insurance", level: "A2"},
{ gender:"n", word: "Werkzeug", english: "tool", level: "A2"},
{ gender:"f", word: "Wolke", english: "cloud", level: "A2"},
{ gender:"m", word: "Wunsch", english: "wish", level: "A2"},
{ gender:"f", word: "Zeitschrift", english: "magazine", level: "A2"},
{ gender:"m", word: "Zentimeter", english: "centimeter", level: "A2"},
{ gender:"f", word: "Zitrone", english: "lemon", level: "A2"},
{ gender:"m", word: "Zucker", english: "sugar", level: "A2"}]


NOUNS.each do | noun |
	n = Noun.find_or_initialize_by( word: noun[:word])
	g = Gender.find_by!(char_desc: noun[:gender])
	level = LanguageLevel.find_by!(level_code: noun[:level])
	n.language_level = level
	n.gender = g
	n.english = noun[:english]
	n.save!	
end